In [177]:
import pandas as pd
import numpy as np
import xgboost as xgb
import joblib
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
pd.set_option('display.max_columns', None)

In [82]:
def calculate_metrics(y_true, y_pred, model_name="Model"):
    """Calculate comprehensive evaluation metrics"""
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    
    return {
        'MAE': mae,
        'MSE': mse,
        'RMSE': rmse,
        'R2': r2
    }

In [74]:
ml_data= {}
ml_data['X_train'] = pd.read_csv('../data/ml_X_train.csv')
ml_data['X_val'] = pd.read_csv('../data/ml_X_val.csv')
ml_data['X_test'] = pd.read_csv('../data/ml_X_test.csv')
ml_data['y_train'] = pd.read_csv('../data/ml_y_train.csv')
ml_data['y_val'] = pd.read_csv('../data/ml_y_val.csv')
ml_data['y_test'] = pd.read_csv('../data/ml_y_test.csv')

In [220]:
# xgb_final_model = joblib.load("../models/xgb_final_model.pkl")
xgb_baseline_model = joblib.load("../models/xgb_model_baseline_model.pkl")

In [78]:
loaded_model = xgb.XGBRegressor()
loaded_model.load_model(r"E:\Programs\COMPANY\Sashflow\project_future_projection\rnd\models\xgboost_advanced_model.json")

In [85]:
p1 = loaded_model.predict(ml_data['X_val'])
p2 = xgb_model.predict(ml_data['X_val'])

In [86]:
print(calculate_metrics(ml_data['y_val'], p1, 'test'))
print(calculate_metrics(ml_data['y_val'], p2, 'test'))

{'MAE': 1449.3096923828125, 'MSE': 4248928.0, 'RMSE': np.float64(2061.2927982215433), 'R2': 0.8378171920776367}
{'MAE': 1449.3096923828125, 'MSE': 4248928.0, 'RMSE': np.float64(2061.2927982215433), 'R2': 0.8378171920776367}

In [224]:
main_df = pd.read_csv('../data/refactored_df.csv')
weather_df = pd.read_csv('../data/weather_data.csv')
trends_df = pd.read_csv('../data/customer_trends.csv')

In [225]:
# Step 1: Data Preparation and Merging
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

print("Loading datasets...")
print(f"Main dataset shape: {main_df.shape}")
print(f"Weather dataset shape: {weather_df.shape}")
print(f"Trends dataset shape: {trends_df.shape}")

# Convert date columns
main_df['Date'] = pd.to_datetime(main_df['Date'])
main_df = main_df[['Date', 'Branch', 'Segment', 'Rating', 'Tonnage', 'Qty', 'Year', 'Month', 'Week']]
weather_df['Date'] = pd.to_datetime(weather_df['Date'])
trends_df['Month'] = pd.to_datetime(trends_df['Month'])

print("\nDate ranges:")
print(f"Main data: {main_df['Date'].min()} to {main_df['Date'].max()}")
print(f"Weather data: {weather_df['Date'].min()} to {weather_df['Date'].max()}")
print(f"Trends data: {trends_df['Month'].min()} to {trends_df['Month'].max()}")

Loading datasets...
Main dataset shape: (147595, 9)
Weather dataset shape: (456, 11)
Trends dataset shape: (82, 2)

Date ranges:
Main data: 2019-04-03 00:00:00 to 2024-03-30 00:00:00
Weather data: 2019-04-01 00:00:00 to 2025-10-01 00:00:00
Trends data: 2019-01-01 00:00:00 to 2025-10-01 00:00:00

In [226]:
grouped_df = (
    main_df.groupby([main_df['Date'].dt.to_period('M').dt.to_timestamp().rename('MonthStart'), 'Branch'])
    .agg({'Qty': 'sum'})
    .reset_index()
)
grouped_df.columns = ['Date', 'Branch', 'Qty']

In [227]:
new_df = (
    main_df.groupby([main_df['Date'].dt.to_period('M').dt.to_timestamp().rename('MonthStart'), 'Branch'])
    .agg({'Qty': 'sum'})
    .reset_index()
)
new_df.columns = ['Date', 'Branch', 'Qty']
new_df = new_df[new_df['Date'] >= '2023-04-01']
new_df.loc[new_df['Date'] >= '2023-04-01', 'Date'] = (
    new_df.loc[new_df['Date'] >= '2023-04-01', 'Date'] + pd.DateOffset(years=1)
)
new_df['Qty']=np.nan

In [228]:
concat = pd.concat([grouped_df, new_df])

In [229]:
concat

          Date Branch      Qty
0   2019-04-01    BLR   2667.0
1   2019-04-01    COK   1756.0
2   2019-04-01    MAA  13121.5
3   2019-04-01    SBD   3564.5
4   2019-04-01   SBD1   5260.0
..         ...    ...      ...
290 2025-03-01    BLR      NaN
291 2025-03-01    COK      NaN
292 2025-03-01    MAA      NaN
293 2025-03-01    SBD      NaN
294 2025-03-01   SBD1      NaN

[355 rows x 3 columns]

In [230]:
trends_df.rename(columns={'Month': 'Date'}, inplace=True)

In [231]:
ml_df = concat.merge(weather_df, on=['Date', 'Branch']).merge(trends_df, on=['Date'])

In [233]:
ml_df['Seasonality_Level'] = ml_df['Date'].dt.month_name().str[:3].map({
    'Mar': 3, 'Dec': 3, 'Feb': 3, 'Apr': 3,
    'May': 2, 'Jan': 2,
    'Jun': 1, 'Jul': 1, 'Aug': 1, 'Sep': 1, 'Oct': 1, 'Nov': 1
})

In [234]:
ml_df

,Date,Branch,Qty,Min Temp,Max Temp,Avg Temp,Min Humidity,Max Humidity,Avg Humidity,Min Wind Speed,Max Wind Speed,Avg Wind Speed,Interest,Seasonality_Level
0,2019-04-01,BLR,2667.0,20.0,36.0,27.991643,13.0,100.0,49.857939,0.0,46.4,10.715181,71,3
1,2019-04-01,MAA,13121.5,26.0,40.0,31.565694,33.0,94.0,70.098611,0.0,27.7,12.295556,71,3
2,2019-04-01,SBD,3564.5,21.0,41.0,30.852273,14.0,94.0,47.340909,0.0,29.5,11.066903,71,3
3,2019-05-01,BLR,2446.5,19.0,36.0,27.343284,18.0,100.0,68.128901,0.0,40.7,12.634783,66,2
4,2019-05-01,MAA,11896.5,27.8,42.0,33.247446,20.0,91.0,66.135753,0.0,42.5,14.206452,66,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,2025-02-01,SBD,NaN,15.0,35.0,25.690923,13.0,100.0,53.346726,0.0,22.3,10.552679,40,3
271,2025-03-01,BLR,NaN,16.0,35.0,25.794624,11.0,98.0,50.341398,0.0,33.5,11.462769,65,3
272,2025-03-01,COK,NaN,23.0,37.0,28.886557,27.0,100.0,76.334426,0.7,22.0,7.503115,65,3
273,2025-03-01,MAA,NaN,22.8,38.4,29.397984,24.0,95.0,73.627688,0.0,25.9,9.904839,65,3
274,2025-03-01,SBD,NaN,17.0,37.0,28.027923,8.0,100.0,46.276479,3.6,25.9,11.624347,65,3

In [235]:
# =============================================================================
# 2. COMPREHENSIVE FEATURE ENGINEERING (FIXED VERSION)
# =============================================================================

print("\n2. COMPREHENSIVE FEATURE ENGINEERING")
print("-" * 50)

# Import required modules
from sklearn.preprocessing import LabelEncoder

def drop_nan_columns(df, threshold=1.0, verbose=True):
    """
    Drop columns with a fraction of NaN values above the given threshold.
    
    Parameters:
        df (pd.DataFrame): Input DataFrame.
        threshold (float): Fraction (0–1). Columns with NaN ratio >= threshold are dropped.
                           Default 1.0 means drop columns that are entirely NaN.
        verbose (bool): Whether to print information about dropped columns.
        
    Returns:
        pd.DataFrame: DataFrame with selected columns dropped.
        list: List of dropped column names.
    """
    # Calculate fraction of missing values per column
    nan_ratio = df.isna().mean()
    
    # Select columns to drop
    drop_cols = nan_ratio[nan_ratio >= threshold].index.tolist()
    
    # Drop them
    df_cleaned = df.drop(columns=drop_cols)
    
    if verbose:
        print(f"Dropped {len(drop_cols)} column(s) with ≥{threshold*100:.0f}% NaN values:")
        if drop_cols:
            print(drop_cols)
        else:
            print("No columns dropped.")
    
    return df_cleaned

def create_ml_features(df):
    """
    Create comprehensive features for machine learning models with proper NaN handling
    """
    print("Creating comprehensive features...")
    
    # Start with the base dataframe
    ml_df = df.copy()
    ml_df = drop_nan_columns(ml_df, 0.5)
    
    # Check data availability for each branch
    branch_counts = ml_df.groupby('Branch').size()
    print(f"  Data points per branch: {dict(branch_counts)}")
    
    # 1. TIME-BASED FEATURES
    print("  Creating time-based features...")
    ml_df['year'] = ml_df['Date'].dt.year
    ml_df['month'] = ml_df['Date'].dt.month
    ml_df['day'] = ml_df['Date'].dt.day
    ml_df['dayofweek'] = ml_df['Date'].dt.dayofweek
    ml_df['dayofyear'] = ml_df['Date'].dt.dayofyear
    ml_df['week'] = ml_df['Date'].dt.isocalendar().week
    ml_df['quarter'] = ml_df['Date'].dt.quarter
    
    # Cyclical encoding for time features
    ml_df['month_sin'] = np.sin(2 * np.pi * ml_df['month'] / 12)
    ml_df['month_cos'] = np.cos(2 * np.pi * ml_df['month'] / 12)
    ml_df['dayofweek_sin'] = np.sin(2 * np.pi * ml_df['dayofweek'] / 7)
    ml_df['dayofweek_cos'] = np.cos(2 * np.pi * ml_df['dayofweek'] / 7)
    ml_df['quarter_sin'] = np.sin(2 * np.pi * ml_df['quarter'] / 4)
    ml_df['quarter_cos'] = np.cos(2 * np.pi * ml_df['quarter'] / 4)
    
    # 2. LAG FEATURES (ADAPTIVE BASED ON DATA AVAILABILITY)
    print("  Creating lag features...")
    # Sort by date and branch for proper lag calculation
    ml_df = ml_df.sort_values(['Branch', 'Date'])
    
    # Use smaller lag periods appropriate for monthly data
    lag_periods = [1, 2, 3, 6, 12]  # months instead of days
    for lag in lag_periods:
        ml_df[f'qty_lag_{lag}m'] = ml_df.groupby('Branch')['Qty'].shift(lag)
        # Only create rolling mean if we have enough data
        if lag <= 3:  # Only for short lags
            ml_df[f'qty_lag_{lag}m_mean'] = ml_df.groupby('Branch')['Qty'].shift(lag).rolling(window=min(3, lag), min_periods=1).mean()
    
    # 3. ROLLING STATISTICS (ADAPTIVE WINDOWS)
    print("  Creating rolling statistics...")
    # Use smaller windows appropriate for monthly data
    rolling_windows = [2, 3, 6, 12]  # months
    for window in rolling_windows:
        # Use min_periods to handle insufficient data gracefully
        ml_df[f'qty_rolling_mean_{window}m'] = ml_df.groupby('Branch')['Qty'].rolling(window=window, min_periods=1).mean().reset_index(0, drop=True)
        ml_df[f'qty_rolling_std_{window}m'] = ml_df.groupby('Branch')['Qty'].rolling(window=window, min_periods=1).std().reset_index(0, drop=True)
        ml_df[f'qty_rolling_max_{window}m'] = ml_df.groupby('Branch')['Qty'].rolling(window=window, min_periods=1).max().reset_index(0, drop=True)
        ml_df[f'qty_rolling_min_{window}m'] = ml_df.groupby('Branch')['Qty'].rolling(window=window, min_periods=1).min().reset_index(0, drop=True)
        ml_df[f'qty_rolling_sum_{window}m'] = ml_df.groupby('Branch')['Qty'].rolling(window=window, min_periods=1).sum().reset_index(0, drop=True)
    
    # 4. EXPANDING STATISTICS
    print("  Creating expanding statistics...")
    ml_df['qty_expanding_mean'] = ml_df.groupby('Branch')['Qty'].expanding().mean().reset_index(0, drop=True)
    ml_df['qty_expanding_std'] = ml_df.groupby('Branch')['Qty'].expanding().std().reset_index(0, drop=True)
    ml_df['qty_expanding_max'] = ml_df.groupby('Branch')['Qty'].expanding().max().reset_index(0, drop=True)
    ml_df['qty_expanding_min'] = ml_df.groupby('Branch')['Qty'].expanding().min().reset_index(0, drop=True)
    
    # 5. SEASONAL FEATURES
    print("  Creating seasonal features...")
    # Monthly seasonality
    monthly_avg = ml_df.groupby('month')['Qty'].mean()
    ml_df['monthly_seasonality'] = ml_df['month'].map(monthly_avg)
    
    # Quarterly seasonality
    quarterly_avg = ml_df.groupby('quarter')['Qty'].mean()
    ml_df['quarterly_seasonality'] = ml_df['quarter'].map(quarterly_avg)
    
    # Day of week seasonality
    dow_avg = ml_df.groupby('dayofweek')['Qty'].mean()
    ml_df['dow_seasonality'] = ml_df['dayofweek'].map(dow_avg)
    
    # 6. WEATHER LAG FEATURES (ADAPTIVE)
    print("  Creating weather lag features...")
    weather_lags = [1, 2, 3, 6]  # months
    for lag in weather_lags:
        ml_df[f'temp_lag_{lag}m'] = ml_df.groupby('Branch')['Avg Temp'].shift(lag)
        ml_df[f'humidity_lag_{lag}m'] = ml_df.groupby('Branch')['Avg Humidity'].shift(lag)
        ml_df[f'wind_lag_{lag}m'] = ml_df.groupby('Branch')['Avg Wind Speed'].shift(lag)
    
    # 7. TRENDS LAG FEATURES
    print("  Creating trends lag features...")
    trends_lags = [1, 2, 3, 6]
    for lag in trends_lags:
        ml_df[f'trends_lag_{lag}m'] = ml_df['Interest'].shift(lag)
    
    # 8. PRODUCT FEATURES
    print("  Creating product features...")
    # Branch encoding
    branch_encoder = LabelEncoder()
    ml_df['branch_encoded'] = branch_encoder.fit_transform(ml_df['Branch'])
    
    # 9. INTERACTION FEATURES
    print("  Creating interaction features...")
    ml_df['temp_humidity_interaction'] = ml_df['Avg Temp'] * ml_df['Avg Humidity']
    ml_df['temp_wind_interaction'] = ml_df['Avg Temp'] * ml_df['Avg Wind Speed']
    
    # 10. STATISTICAL FEATURES
    print("  Creating statistical features...")
    # Temperature statistics
    ml_df['temp_range'] = ml_df['Max Temp'] - ml_df['Min Temp']
    ml_df['humidity_range'] = ml_df['Max Humidity'] - ml_df['Min Humidity']
    ml_df['wind_range'] = ml_df['Max Wind Speed'] - ml_df['Min Wind Speed']
    
    # Temperature deviation from historical average
    temp_avg = ml_df.groupby('month')['Avg Temp'].transform('mean')
    ml_df['temp_deviation'] = ml_df['Avg Temp'] - temp_avg
    
    # Humidity deviation from historical average
    humidity_avg = ml_df.groupby('month')['Avg Humidity'].transform('mean')
    ml_df['humidity_deviation'] = ml_df['Avg Humidity'] - humidity_avg
    
    # 11. BUSINESS FEATURES
    print("  Creating business features...")
    # Days since last sale (convert to months for monthly data)
    ml_df['months_since_last_sale'] = ml_df.groupby('Branch')['Date'].diff().dt.days / 30.44  # Approximate days per month
    
    # Sales momentum (recent vs historical average) - handle division by zero
    ml_df['sales_momentum_3m'] = np.where(
        ml_df['qty_expanding_mean'] != 0,
        ml_df['qty_rolling_mean_3m'] / ml_df['qty_expanding_mean'],
        1.0  # Default to 1 if no historical data
    )
    ml_df['sales_momentum_6m'] = np.where(
        ml_df['qty_expanding_mean'] != 0,
        ml_df['qty_rolling_mean_6m'] / ml_df['qty_expanding_mean'],
        1.0
    )
    
    # Market share by branch
    branch_total = ml_df.groupby('Date')['Qty'].transform('sum')
    ml_df['branch_market_share'] = np.where(
        branch_total != 0,
        ml_df['Qty'] / branch_total,
        0.0
    )
    
    # 12. HANDLE REMAINING NaN VALUES
    print("  Handling remaining NaN values...")
    
    # Fill NaN values in lag features with 0 (no previous data)
    lag_cols = [col for col in ml_df.columns if 'lag' in col]
    ml_df[lag_cols] = ml_df[lag_cols].fillna(0)
    
    # Fill NaN values in rolling features with the current value or mean
    rolling_cols = [col for col in ml_df.columns if 'rolling' in col]
    for col in rolling_cols:
        if col.endswith('_mean') or col.endswith('_sum'):
            ml_df[col] = ml_df[col].fillna(ml_df['Qty'])
        else:
            ml_df[col] = ml_df[col].fillna(ml_df[col].mean())
    
    # Fill NaN values in expanding features
    expanding_cols = [col for col in ml_df.columns if 'expanding' in col]
    ml_df[expanding_cols] = ml_df[expanding_cols].fillna(ml_df['Qty'])
    
    # Fill NaN values in other features
    other_nan_cols = ml_df.columns[ml_df.isnull().any()].tolist()
    for col in other_nan_cols:
        if ml_df[col].dtype in ['int64', 'float64']:
            ml_df[col] = ml_df[col].fillna(ml_df[col].median())
        else:
            ml_df[col] = ml_df[col].fillna(ml_df[col].mode()[0] if not ml_df[col].mode().empty else 0)
    
    print(f"  Feature engineering completed!")
    print(f"  Total features created: {ml_df.shape[1]}")
    
    return ml_df

# Apply feature engineering
ml_df = create_ml_features(ml_df)

# Display feature categories
feature_categories = {
    'Time-based': [col for col in ml_df.columns if any(x in col for x in ['year', 'month', 'day', 'week', 'quarter', 'sin', 'cos'])],
    'Lag features': [col for col in ml_df.columns if 'lag' in col],
    'Rolling statistics': [col for col in ml_df.columns if 'rolling' in col],
    'Expanding statistics': [col for col in ml_df.columns if 'expanding' in col],
    'Weather features': [col for col in ml_df.columns if any(x in col for x in ['Temp', 'Humidity', 'Wind'])],
    'Trends features': [col for col in ml_df.columns if 'trends' in col or 'Interest' in col],
    'Product features': [col for col in ml_df.columns if any(x in col for x in ['branch'])],
    'Interaction features': [col for col in ml_df.columns if 'interaction' in col],
    'Statistical features': [col for col in ml_df.columns if any(x in col for x in ['range', 'deviation', 'momentum'])],
    'Business features': [col for col in ml_df.columns if any(x in col for x in ['market_share', 'days_since'])],
}

print(f"\nFeature Categories:")
for category, features in feature_categories.items():
    print(f"  {category}: {len(features)} features")

# Check for missing values
print(f"\nMissing Values Analysis:")
missing_values = ml_df.isnull().sum()
missing_percentage = (missing_values / len(ml_df)) * 100
missing_summary = pd.DataFrame({
    'Missing Count': missing_values,
    'Missing Percentage': missing_percentage
}).sort_values('Missing Count', ascending=False)

print(missing_summary[missing_summary['Missing Count'] > 0].head(10))

2. COMPREHENSIVE FEATURE ENGINEERING
--------------------------------------------------
Creating comprehensive features...
Dropped 0 column(s) with ≥50% NaN values:
No columns dropped.
  Data points per branch: {'BLR': np.int64(71), 'COK': np.int64(62), 'MAA': np.int64(71), 'SBD': np.int64(71)}
  Creating time-based features...
  Creating lag features...
  Creating rolling statistics...
  Creating expanding statistics...
  Creating seasonal features...
  Creating weather lag features...
  Creating trends lag features...
  Creating product features...
  Creating interaction features...
  Creating statistical features...
  Creating business features...
  Handling remaining NaN values...
  Feature engineering completed!
  Total features created: 90

Feature Categories:
  Time-based: 16 features
  Lag features: 24 features
  Rolling statistics: 20 features
  Expanding statistics: 4 features
  Weather features: 9 features
  Trends features: 5 features
  Product features: 2 features
  Interaction features: 2 features
  Statistical features: 7 features
  Business features: 1 features

Missing Values Analysis:
Empty DataFrame
Columns: [Missing Count, Missing Percentage]
Index: []

In [237]:
# Test the fixed feature engineering function
print("Testing the fixed feature engineering function...")
print("=" * 60)

# Apply the fixed feature engineering
ml_df_fixed = create_ml_features(ml_df)

# Display feature categories
feature_categories = {
    'Time-based': [col for col in ml_df_fixed.columns if any(x in col for x in ['year', 'month', 'day', 'week', 'quarter', 'sin', 'cos'])],
    'Lag features': [col for col in ml_df_fixed.columns if 'lag' in col],
    'Rolling statistics': [col for col in ml_df_fixed.columns if 'rolling' in col],
    'Expanding statistics': [col for col in ml_df_fixed.columns if 'expanding' in col],
    'Weather features': [col for col in ml_df_fixed.columns if any(x in col for x in ['Temp', 'Humidity', 'Wind'])],
    'Trends features': [col for col in ml_df_fixed.columns if 'trends' in col or 'Interest' in col],
    'Product features': [col for col in ml_df_fixed.columns if any(x in col for x in ['branch'])],
    'Interaction features': [col for col in ml_df_fixed.columns if 'interaction' in col],
    'Statistical features': [col for col in ml_df_fixed.columns if any(x in col for x in ['range', 'deviation', 'momentum'])],
    'Business features': [col for col in ml_df_fixed.columns if any(x in col for x in ['market_share', 'months_since'])],
}

print(f"\nFeature Categories:")
for category, features in feature_categories.items():
    print(f"  {category}: {len(features)} features")

# Check for missing values
print(f"\nMissing Values Analysis:")
missing_values = ml_df_fixed.isnull().sum()
missing_percentage = (missing_values / len(ml_df_fixed)) * 100
missing_summary = pd.DataFrame({
    'Missing Count': missing_values,
    'Missing Percentage': missing_percentage
}).sort_values('Missing Count', ascending=False)

# Show only columns with missing values
missing_cols = missing_summary[missing_summary['Missing Count'] > 0]
if len(missing_cols) > 0:
    print("Columns with missing values:")
    print(missing_cols.head(10))
else:
    print("✅ No missing values found!")

print(f"\nData shape: {ml_df_fixed.shape}")
print(f"Total features: {ml_df_fixed.shape[1]}")
print(f"Total samples: {ml_df_fixed.shape[0]}")

# Show sample of the data
print(f"\nSample of processed data:")
print(ml_df_fixed.head())

Testing the fixed feature engineering function...
============================================================
Creating comprehensive features...
Dropped 0 column(s) with ≥50% NaN values:
No columns dropped.
  Data points per branch: {'BLR': np.int64(71), 'COK': np.int64(62), 'MAA': np.int64(71), 'SBD': np.int64(71)}
  Creating time-based features...
  Creating lag features...
  Creating rolling statistics...
  Creating expanding statistics...
  Creating seasonal features...
  Creating weather lag features...
  Creating trends lag features...
  Creating product features...
  Creating interaction features...
  Creating statistical features...
  Creating business features...
  Handling remaining NaN values...
  Feature engineering completed!
  Total features created: 90

Feature Categories:
  Time-based: 16 features
  Lag features: 24 features
  Rolling statistics: 20 features
  Expanding statistics: 4 features
  Weather features: 9 features
  Trends features: 5 features
  Product features: 2 features
  Interaction features: 2 features
  Statistical features: 7 features
  Business features: 2 features

Missing Values Analysis:
✅ No missing values found!

Data shape: (275, 90)
Total features: 90
Total samples: 275

Sample of processed data:
         Date Branch     Qty  Min Temp  Max Temp   Avg Temp  Min Humidity  \
0  2019-04-01    BLR  2667.0      20.0      36.0  27.991643          13.0
3  2019-05-01    BLR  2446.5      19.0      36.0  27.343284          18.0
6  2019-06-01    BLR  1103.0      20.0      33.0  25.694986          36.0
9  2019-07-01    BLR  1222.5      20.0      31.0  24.534600          38.0
12 2019-08-01    BLR  1017.0      20.0      31.0  23.418354          38.0

    Max Humidity  Avg Humidity  Min Wind Speed  Max Wind Speed  \
0          100.0     49.857939             0.0            46.4
3          100.0     68.128901             0.0            40.7
6          100.0     78.798050             1.8            40.7
9          100.0     80.464043             3.6            44.6
12         100.0     88.310391             1.8            48.2

    Avg Wind Speed  Interest  Seasonality_Level  year  month  day  dayofweek  \
0        10.715181        71                  3  2019      4    1          0
3        12.634783        66                  2  2019      5    1          2
6        19.437744        58                  1  2019      6    1          5
9        22.617910        38                  1  2019      7    1          0
12       22.293243        32                  1  2019      8    1          3

    dayofyear  week  quarter     month_sin  month_cos  dayofweek_sin  \
0          91    14        2  8.660254e-01  -0.500000       0.000000
3         121    18        2  5.000000e-01  -0.866025       0.974928
6         152    22        2  1.224647e-16  -1.000000      -0.974928
9         182    27        3 -5.000000e-01  -0.866025       0.000000
12        213    31        3 -8.660254e-01  -0.500000       0.433884

    dayofweek_cos   quarter_sin   quarter_cos  qty_lag_1m  qty_lag_1m_mean  \
0        1.000000  1.224647e-16 -1.000000e+00         0.0              0.0
3       -0.222521  1.224647e-16 -1.000000e+00      2667.0           2667.0
6       -0.222521  1.224647e-16 -1.000000e+00      2446.5           2446.5
9        1.000000 -1.000000e+00 -1.836970e-16      1103.0           1103.0
12      -0.900969 -1.000000e+00 -1.836970e-16      1222.5           1222.5

    qty_lag_2m  qty_lag_2m_mean  qty_lag_3m  qty_lag_3m_mean  qty_lag_6m  \
0          0.0             0.00         0.0             0.00         0.0
3          0.0             0.00         0.0             0.00         0.0
6       2667.0          2667.00         0.0             0.00         0.0
9       2446.5          2556.75      2667.0          2667.00         0.0
12      1103.0          1774.75      2446.5          2556.75         0.0

    qty_lag_12m  qty_rolling_mean_2m  qty_rolling_std_2m  qty_rolling_max_2m  \
0           0.0              2667.00         1600.238745              2667.0
3           0.0              2556.75          155.917045              2667.0
6           0.0              1774.75          949.997961              2446.5
9           0.0              1162.75           84.499260              1222.5
12          0.0              1119.75          145.310444              1222.5

    qty_rolling_min_2m  qty_rolling_sum_2m  qty_rolling_mean_3m  \
0               2667.0              2667.0          2667.000000
3               2446.5              5113.5          2556.750000
6               1103.0              3549.5          2072.166667
9               1103.0              2325.5          1590.666667
12              1017.0              2239.5          1114.166667

    qty_rolling_std_3m  qty_rolling_max_3m  qty_rolling_min_3m  \
0          1887.316530              2667.0              2667.0
3           155.917045              2667.0              2446.5
6           846.532978              2667.0              1103.0
9           743.577893              2446.5              1103.0
12          103.204086              1222.5              1017.0

    qty_rolling_sum_3m  qty_rolling_mean_6m  qty_rolling_std_6m  \
0               2667.0          2667.000000         2396.134476
3               5113.5          2556.750000          155.917045
6               6216.5          2072.166667          846.532978
9               4772.0          1859.750000          811.312979
12              3342.5          1691.200000          797.318678

    qty_rolling_max_6m  qty_rolling_min_6m  qty_rolling_sum_6m  \
0               2667.0              2667.0              2667.0
3               2667.0              2446.5              5113.5
6               2667.0              1103.0              6216.5
9               2667.0              1103.0              7439.0
12              2667.0              1017.0              8456.0

    qty_rolling_mean_12m  qty_rolling_std_12m  qty_rolling_max_12m  \
0            2667.000000          2898.487767               2667.0
3            2556.750000           155.917045               2667.0
6            2072.166667           846.532978               2667.0
9            1859.750000           811.312979               2667.0
12           1691.200000           797.318678               2667.0

    qty_rolling_min_12m  qty_rolling_sum_12m  qty_expanding_mean  \
0                2667.0               2667.0         2667.000000
3                2446.5               5113.5         2556.750000
6                1103.0               6216.5         2072.166667
9                1103.0               7439.0         1859.750000
12               1017.0               8456.0         1691.200000

    qty_expanding_std  qty_expanding_max  qty_expanding_min  \
0         1740.059693             2667.0             2667.0
3          155.917045             2667.0             2446.5
6          846.532978             2667.0             1103.0
9          811.312979             2667.0             1103.0
12         797.318678             2667.0             1017.0

    monthly_seasonality  quarterly_seasonality  dow_seasonality  temp_lag_1m  \
0           7434.368421            4631.123077      4106.321429     0.000000
3           4061.217391            4631.123077      4773.453488    27.991643
6           2885.304348            4631.123077      3595.895349    27.343284
9           2344.173913            2819.217391      4106.321429    25.694986
12          2736.217391            2819.217391      5158.414286    24.534600

    humidity_lag_1m  wind_lag_1m  temp_lag_2m  humidity_lag_2m  wind_lag_2m  \
0          0.000000     0.000000     0.000000         0.000000     0.000000
3         49.857939    10.715181     0.000000         0.000000     0.000000
6         68.128901    12.634783    27.991643        49.857939    10.715181
9         78.798050    19.437744    27.343284        68.128901    12.634783
12        80.464043    22.617910    25.694986        78.798050    19.437744

    temp_lag_3m  humidity_lag_3m  wind_lag_3m  temp_lag_6m  humidity_lag_6m  \
0      0.000000         0.000000     0.000000          0.0              0.0
3      0.000000         0.000000     0.000000          0.0              0.0
6      0.000000         0.000000     0.000000          0.0              0.0
9     27.991643        49.857939    10.715181          0.0              0.0
12    27.343284        68.128901    12.634783          0.0              0.0

    wind_lag_6m  trends_lag_1m  trends_lag_2m  trends_lag_3m  trends_lag_6m  \
0           0.0            0.0            0.0            0.0            0.0
3           0.0           71.0            0.0            0.0            0.0
6           0.0           66.0           71.0            0.0            0.0
9           0.0           58.0           66.0           71.0            0.0
12          0.0           38.0           58.0           66.0            0.0

    branch_encoded  temp_humidity_interaction  temp_wind_interaction  \
0                0                1395.605644             299.935528
3                0                1862.867859             345.476444
6                0                2024.714801             499.452554
9                0                1974.153098             554.921380
12               0                2068.083969             522.071053

    temp_range  humidity_range  wind_range  temp_deviation  \
0         16.0            87.0        46.4       -1.517627
3         17.0            82.0        40.7       -2.173943
6         13.0            64.0        38.9       -2.445067
9         11.0            62.0        41.0       -2.005176
12        11.0            62.0        46.4       -3.230404

    humidity_deviation  months_since_last_sale  sales_momentum_3m  \
0           -12.569413                1.018397           1.000000
3            -0.741631                0.985545           1.000000
6             3.961861                1.018397           1.000000
9            -0.970494                0.985545           0.855312
12            7.490167                1.018397           0.658802

    sales_momentum_6m  branch_market_share
0                 1.0             0.137808
3                 1.0             0.124100
6                 1.0             0.103704
9                 1.0             0.161450
12                1.0             0.138944

In [238]:
ml_df

,Date,Branch,Qty,Min Temp,Max Temp,Avg Temp,Min Humidity,Max Humidity,Avg Humidity,Min Wind Speed,Max Wind Speed,Avg Wind Speed,Interest,Seasonality_Level,year,month,day,dayofweek,dayofyear,week,quarter,month_sin,month_cos,dayofweek_sin,dayofweek_cos,quarter_sin,quarter_cos,qty_lag_1m,qty_lag_1m_mean,qty_lag_2m,qty_lag_2m_mean,qty_lag_3m,qty_lag_3m_mean,qty_lag_6m,qty_lag_12m,qty_rolling_mean_2m,qty_rolling_std_2m,qty_rolling_max_2m,qty_rolling_min_2m,qty_rolling_sum_2m,qty_rolling_mean_3m,qty_rolling_std_3m,qty_rolling_max_3m,qty_rolling_min_3m,qty_rolling_sum_3m,qty_rolling_mean_6m,qty_rolling_std_6m,qty_rolling_max_6m,qty_rolling_min_6m,qty_rolling_sum_6m,qty_rolling_mean_12m,qty_rolling_std_12m,qty_rolling_max_12m,qty_rolling_min_12m,qty_rolling_sum_12m,qty_expanding_mean,qty_expanding_std,qty_expanding_max,qty_expanding_min,monthly_seasonality,quarterly_seasonality,dow_seasonality,temp_lag_1m,humidity_lag_1m,wind_lag_1m,temp_lag_2m,humidity_lag_2m,wind_lag_2m,temp_lag_3m,humidity_lag_3m,wind_lag_3m,temp_lag_6m,humidity_lag_6m,wind_lag_6m,trends_lag_1m,trends_lag_2m,trends_lag_3m,trends_lag_6m,branch_encoded,temp_humidity_interaction,temp_wind_interaction,temp_range,humidity_range,wind_range,temp_deviation,humidity_deviation,months_since_last_sale,sales_momentum_3m,sales_momentum_6m,branch_market_share
0,2019-04-01,BLR,2667.0,20.0,36.0,27.991643,13.0,100.0,49.857939,0.0,46.4,10.715181,71,3,2019,4,1,0,91,14,2,8.660254e-01,-5.000000e-01,0.000000,1.000000,1.224647e-16,-1.000000e+00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,2667.000000,1786.969817,2667.00000,2667.000000,2667.000000,2667.000000,2098.133360,2667.000000,2667.000000,2667.000000,2667.000000,2606.522192,2667.000000,2667.000000,2667.000000,2667.000000,2997.037829,2667.000000,2667.000000,2667.000000,2667.000000,1776.836502,2667.0,2667.0,8593.533333,4980.622642,4346.044118,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0,1395.605644,299.935528,16.0,87.0,46.4,-1.517627,-12.569413,1.018397,1.000000,1.00000,0.137808
3,2019-05-01,BLR,2446.5,19.0,36.0,27.343284,18.0,100.0,68.128901,0.0,40.7,12.634783,66,2,2019,5,1,2,121,18,2,5.000000e-01,-8.660254e-01,0.974928,-0.222521,1.224647e-16,-1.000000e+00,2667.0,2667.0,0.0,0.00,0.0,0.00,0.0,0.0,2556.750000,155.917045,2667.00000,2446.500000,5113.500000,2556.750000,155.917045,2667.000000,2446.500000,5113.500000,2556.750000,155.917045,2667.000000,2446.500000,5113.500000,2556.750000,155.917045,2667.000000,2446.500000,5113.500000,2556.750000,155.917045,2667.0,2446.5,4266.210526,4980.622642,5158.814286,27.991643,49.857939,10.715181,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,71.0,0.0,0.0,0.0,0,1862.867859,345.476444,17.0,82.0,40.7,-2.173943,-0.741631,0.985545,1.000000,1.00000,0.124100
6,2019-06-01,BLR,1103.0,20.0,33.0,25.694986,36.0,100.0,78.798050,1.8,40.7,19.437744,58,1,2019,6,1,5,152,22,2,1.224647e-16,-1.000000e+00,-0.974928,-0.222521,1.224647e-16,-1.000000e+00,2446.5,2446.5,2667.0,2667.00,0.0,0.00,0.0,0.0,1774.750000,949.997961,2446.50000,1103.000000,3549.500000,2072.166667,846.532978,2667.000000,1103.000000,6216.500000,2072.166667,846.532978,2667.000000,1103.000000,6216.500000,2072.166667,846.532978,2667.000000,1103.000000,6216.500000,2072.166667,846.532978,2667.0,1103.0,2842.736842,4980.622642,3792.693548,27.343284,68.128901,12.634783,27.991643,49.857939,10.715181,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,66.0,71.0,0.0,0.0,0,2024.714801,499.452554,13.0,64.0,38.9,-2.445067,3.961861,1.018397,1.000000,1.00000,0.103704
9,2019-07-01,BLR,1222.5,20.0,31.0,24.534600,38.0,100.0,80.464043,3.6,44.6,22.617910,38,1,2019,7,1,0,182,27,3,-5.000000e-01,-8.660254e-01,0.000000,1.000000,-1.000000e+00,-1.836970e-16,1103.0,1103.0,2446.5,2556.75,2667.0,2667.00,0.0,0.0,1162.750000,84.499260,1222.50000,1103.000000,2325.500000,1590.666667,743.577893,2446.500000,1103.000000,4772.000000,1859.750000,811.312979,2667.000000,1103.000000,7439.000000,1859.750000,811.312979,2667.000000,1103.000000,7439.000000,1859.750000,811.312979,2667.0,1103.0,2187.684211,2762.736842,4346.044118,25.694986,78.798050,19.437744,27.343284,68.128901,12.634783,27.991643,49.857939,10.715181,0.000000,0.000000,0.000000,58.0,66.0,71.0,0.0,0,1974.153098,554.921380,11.0,62.0,41.0,-2.005176,-0.970494,0.985545,0.855312,1.00000,0.161450
12,2019-08-01,BLR,1017.0,20.0,31.0,23.418354,38.0,100.0,88.310391,1.8,48.2,22.293243,32,1,2019,8,1,3,213,31,3,-8.660254e-01,-5.000000e-01,0.433884,-0.900969,-1.000000e+00,-1.836970e-16,1222.5,1222.5,1103.0,1774.75,2446.5,2556.75,0.0,0.0,1119.750000,145.310444,1222.50000,1017.000000,2239.500000,1114.166667,103.204086,1222.500000,1017.000000,3342.500000,1691.200000,797.318678,2667.000000,1017.000000,8456.000000,1691.200000,797.318678,2667.000000,1017.000000,8456.000000,1691.200000,797.318678,2667.0,1017.0,2662.263158,2762.736842,5425.629032,24.534600,80.464043,22.617910,25.694986,78.798050,19.437744,27.343284,68.128901,12.634783,0.000000,0.000000,0.000000,38.0,58.0,66.0,0.0,0,2068.083969,522.071053,11.0,62.0,46.4,-3.230404,7.490167,1.018397,0.658802,1.00000,0.138944
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,2024-11-01,SBD,3087.5,12.0,32.0,23.562917,24.0,100.0,67.526389,1.8,22.3,10.373472,28,1,2024,11,1,4,306,44,4,-5.000000e-01,8.660254e-01,-0.433884,-0.900969,-2.449294e-16,1.000000e+00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,6021.0,4812.768398,1786.969817,6032.58658,3592.950216,9267.917749,4889.542553,2098.133360,7001.442553,3236.021277,13665.248936,5036.297065,2606.522192,8981.825911,2644.362348,26002.700405,16250.375000,8133.036860,23411.000000,6385.000000,65001.500000,6046.796610,5120.130809,23411.0,1307.0,2786.289474,4712.333333,6356.557143,25.724059,79.373656,11.020968,25.093305,83.463040,15.950767,25.889373,82.211172,15.790599,30.941129,56.587366,14.042473,33.0,36.0,38.0,100.0,3,1591.118674,244.429262,20.0,76.0,20.5,-1.307203,-13.984615,1.018397,1.076120,1.09796,0.000000
262,2024-12-01,SBD,3087.5,9.0,30.0,22.097301,23.0,100.0,79.572200,0.0,24.1,10.787449,26,3,2024,12,1,6,336,48,4,-2.449294e-16,1.000000e+00,-0.781831,0.623490,-2.449294e-16,1.000000e+00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,23411.0,4812.768398,1786.969817,6032.58658,3592.950216,9267.917749,4889.542553,2098.133360,7001.442553,3236.021277,13665.248936,5036.297065,2606.522192,8981.825911,2644.362348,26002.700405,13863.500000,8064.514818,22408.000000,6385.000000,41590.500000,6046.796610,5120.130809,23411.0,1307.0,8615.684211,4712.333333,3664.616667,23.562917,67.526389,10.373472,25.724059,79.373656,11.020968,25.093305,83.463040,15.950767,27.681111,72.966667,16.512361,28.0,33.0,36.0,68.0,3,1758.330844,238.373516,21.0,77.0,24.1,-1.911418,0.667451,0.985545,1.076120,1.09796,0.000000
266,2025-01-01,SBD,3087.5,14.0,33.0,22.047312,17.0,100.0,63.505376,3.6,22.3,10.954301,30,2,2025,1,1,2,1,1,1,5.000000e-01,8.660254e-01,0.974928,-0.222521,1.000000e+00,6.123234e-17,0.0,0.0,0.0,0.00,0.0,0.00,0.0,6385.0,4812.768398,1786.969817,6032.58658,3592.950216,9267.917749,4889.542553,2098.133360,7001.442553,3236.021277,13665.248936,5036.297065,2606.522192,8981.825911,2644.362348,26002.700405,17602.750000,6795.649721,22408.000000,12797.500000,35205.500000,6046.796610,5120.130809,23411.0,1307.0,4080.575000,6339.875000,5158.814286,22.097301,79.572200,10.787449,23.562917,67.526389,10.373472,25.724059,79.373656,11.020968,25.463710,82.231183,20.763038,26.0,28.0,33.0,44.0,3,1400.122835,241.512892,19.0,83.0,18.7,-2.258887,-9.107938,1.018397,1.076120,1.09796,0.000000
270,2025-02-01,SBD,3087.5,15.0,35.0,25.690923,13.0,100.0,53.346726,0.0,22.3,10.552679,40,3,2025,2,1,5,32,5,1,8.660254e-01,5.000000e-01,-0.974928,-0.222521,1.000000e+00,6.123234e-17,0.0,0.0,0.0,0.00,0.0,0.00,0.0,12797.5,4812.768398,1786.969817,6032.58658,3592.950216,9267.917749,4889.542553,2098.133360,7001.442553,3236.021277,13665.248936,5036.297065,2606.522192,8981.825911,2644.362348,26002.700405,22408.000000,2997.037829,22408.000000,22408.000000,22408.000000,6046.796610,5120.130809,23411.0,1307.0,7107.525000,6339.875000,3792.693548,22.047312,63.505376,10.954301,22.097301,79.572200,10.787449,23.562917,67.526389,10.373472,25.889373,82.211172,15.790599,30.0,26.0,28.0,38.0,3,1370.526615,271.108049,20.0,87.0,22.3,0.106186,-10.758778,1.018397,1.076120,1.09796,0.000000
274,2025-03-01,SBD,3087.5,17.0,37.0,28.027923,8.0,100.0,46.276479,3.6,25.9,11.624347,65,3,2025,3,1,5,60,9,1,1.000000e+00,6.123234e-17,-0.974928,-0.222521,1.000000e+00,6.123234e-17,0.0,0.0,0.0,0.00,0.0,0.00,0.0,22408.0,4812.768398,1786.969817,6032.58658,3592.950216,9267.917749,4889.542553,2098.133360,7001.442553,3236.021277,13665.248936,5036.297065,2606.522192,8981.825911,2644.362348,26002.700405,5150.418029,2997.037829,10997.588561,2295.468635,47399.756458,6046.796610,5120.130809,23411.0,1307.0,7831.525000,6339.875000,3792.693548,25.690923,53.346726,10.552679,22.047312,63.505376,10.954301,22.097301,79.572200,10.787449,25.093305,83.463040,15.950767,40.0,30.0,26.0,36.0,3,1297.033580,325.806292,20.0,92.0,22.3,0.193629,-15.570753,0.919842,1.076120,1.09796,0.000000

In [191]:
# Test the fixed feature engineering function
print("Testing the fixed feature engineering function...")
print("=" * 60)

# Apply the fixed feature engineering
ml_df_fixed = create_ml_features(ml_df)

# Display feature categories
feature_categories = {
    'Time-based': [col for col in ml_df_fixed.columns if any(x in col for x in ['year', 'month', 'day', 'week', 'quarter', 'sin', 'cos'])],
    'Lag features': [col for col in ml_df_fixed.columns if 'lag' in col],
    'Rolling statistics': [col for col in ml_df_fixed.columns if 'rolling' in col],
    'Expanding statistics': [col for col in ml_df_fixed.columns if 'expanding' in col],
    'Weather features': [col for col in ml_df_fixed.columns if any(x in col for x in ['Temp', 'Humidity', 'Wind'])],
    'Trends features': [col for col in ml_df_fixed.columns if 'trends' in col or 'Interest' in col],
    'Product features': [col for col in ml_df_fixed.columns if any(x in col for x in ['branch'])],
    'Interaction features': [col for col in ml_df_fixed.columns if 'interaction' in col],
    'Statistical features': [col for col in ml_df_fixed.columns if any(x in col for x in ['range', 'deviation', 'momentum'])],
    'Business features': [col for col in ml_df_fixed.columns if any(x in col for x in ['market_share', 'months_since'])],
}

print(f"\nFeature Categories:")
for category, features in feature_categories.items():
    print(f"  {category}: {len(features)} features")

# Check for missing values
print(f"\nMissing Values Analysis:")
missing_values = ml_df_fixed.isnull().sum()
missing_percentage = (missing_values / len(ml_df_fixed)) * 100
missing_summary = pd.DataFrame({
    'Missing Count': missing_values,
    'Missing Percentage': missing_percentage
}).sort_values('Missing Count', ascending=False)

# Show only columns with missing values
missing_cols = missing_summary[missing_summary['Missing Count'] > 0]
if len(missing_cols) > 0:
    print("Columns with missing values:")
    print(missing_cols.head(10))
else:
    print("✅ No missing values found!")

print(f"\nData shape: {ml_df_fixed.shape}")
print(f"Total features: {ml_df_fixed.shape[1]}")
print(f"Total samples: {ml_df_fixed.shape[0]}")

# Show sample of the data
print(f"\nSample of processed data:")
print(ml_df_fixed.head())

Testing the fixed feature engineering function...
============================================================
Creating comprehensive features...
Dropped 0 column(s) with ≥50% NaN values:
No columns dropped.
  Data points per branch: {'BLR': np.int64(71), 'COK': np.int64(62), 'MAA': np.int64(71), 'SBD': np.int64(71)}
  Creating time-based features...
  Creating lag features...
  Creating rolling statistics...
  Creating expanding statistics...
  Creating seasonal features...
  Creating weather lag features...
  Creating trends lag features...
  Creating product features...
  Creating interaction features...
  Creating statistical features...
  Creating business features...
  Handling remaining NaN values...
  Feature engineering completed!
  Total features created: 90

Feature Categories:
  Time-based: 16 features
  Lag features: 24 features
  Rolling statistics: 20 features
  Expanding statistics: 4 features
  Weather features: 9 features
  Trends features: 5 features
  Product features: 2 features
  Interaction features: 2 features
  Statistical features: 7 features
  Business features: 2 features

Missing Values Analysis:
✅ No missing values found!

Data shape: (275, 90)
Total features: 90
Total samples: 275

Sample of processed data:
         Date Branch     Qty  Min Temp  Max Temp   Avg Temp  Min Humidity  \
0  2019-04-01    BLR  2667.0      20.0      36.0  27.991643          13.0
3  2019-05-01    BLR  2446.5      19.0      36.0  27.343284          18.0
6  2019-06-01    BLR  1103.0      20.0      33.0  25.694986          36.0
9  2019-07-01    BLR  1222.5      20.0      31.0  24.534600          38.0
12 2019-08-01    BLR  1017.0      20.0      31.0  23.418354          38.0

    Max Humidity  Avg Humidity  Min Wind Speed  Max Wind Speed  \
0          100.0     49.857939             0.0            46.4
3          100.0     68.128901             0.0            40.7
6          100.0     78.798050             1.8            40.7
9          100.0     80.464043             3.6            44.6
12         100.0     88.310391             1.8            48.2

    Avg Wind Speed  Interest  Seasonality_Level  year  month  day  dayofweek  \
0        10.715181        71                  3  2019      4    1          0
3        12.634783        66                  2  2019      5    1          2
6        19.437744        58                  1  2019      6    1          5
9        22.617910        38                  1  2019      7    1          0
12       22.293243        32                  1  2019      8    1          3

    dayofyear  week  quarter     month_sin  month_cos  dayofweek_sin  \
0          91    14        2  8.660254e-01  -0.500000       0.000000
3         121    18        2  5.000000e-01  -0.866025       0.974928
6         152    22        2  1.224647e-16  -1.000000      -0.974928
9         182    27        3 -5.000000e-01  -0.866025       0.000000
12        213    31        3 -8.660254e-01  -0.500000       0.433884

    dayofweek_cos   quarter_sin   quarter_cos  qty_lag_1m  qty_lag_1m_mean  \
0        1.000000  1.224647e-16 -1.000000e+00         0.0              0.0
3       -0.222521  1.224647e-16 -1.000000e+00      2667.0           2667.0
6       -0.222521  1.224647e-16 -1.000000e+00      2446.5           2446.5
9        1.000000 -1.000000e+00 -1.836970e-16      1103.0           1103.0
12      -0.900969 -1.000000e+00 -1.836970e-16      1222.5           1222.5

    qty_lag_2m  qty_lag_2m_mean  qty_lag_3m  qty_lag_3m_mean  qty_lag_6m  \
0          0.0             0.00         0.0             0.00         0.0
3          0.0             0.00         0.0             0.00         0.0
6       2667.0          2667.00         0.0             0.00         0.0
9       2446.5          2556.75      2667.0          2667.00         0.0
12      1103.0          1774.75      2446.5          2556.75         0.0

    qty_lag_12m  qty_rolling_mean_2m  qty_rolling_std_2m  qty_rolling_max_2m  \
0           0.0              2667.00         1600.238745              2667.0
3           0.0              2556.75          155.917045              2667.0
6           0.0              1774.75          949.997961              2446.5
9           0.0              1162.75           84.499260              1222.5
12          0.0              1119.75          145.310444              1222.5

    qty_rolling_min_2m  qty_rolling_sum_2m  qty_rolling_mean_3m  \
0               2667.0              2667.0          2667.000000
3               2446.5              5113.5          2556.750000
6               1103.0              3549.5          2072.166667
9               1103.0              2325.5          1590.666667
12              1017.0              2239.5          1114.166667

    qty_rolling_std_3m  qty_rolling_max_3m  qty_rolling_min_3m  \
0          1887.316530              2667.0              2667.0
3           155.917045              2667.0              2446.5
6           846.532978              2667.0              1103.0
9           743.577893              2446.5              1103.0
12          103.204086              1222.5              1017.0

    qty_rolling_sum_3m  qty_rolling_mean_6m  qty_rolling_std_6m  \
0               2667.0          2667.000000         2396.134476
3               5113.5          2556.750000          155.917045
6               6216.5          2072.166667          846.532978
9               4772.0          1859.750000          811.312979
12              3342.5          1691.200000          797.318678

    qty_rolling_max_6m  qty_rolling_min_6m  qty_rolling_sum_6m  \
0               2667.0              2667.0              2667.0
3               2667.0              2446.5              5113.5
6               2667.0              1103.0              6216.5
9               2667.0              1103.0              7439.0
12              2667.0              1017.0              8456.0

    qty_rolling_mean_12m  qty_rolling_std_12m  qty_rolling_max_12m  \
0            2667.000000          2898.487767               2667.0
3            2556.750000           155.917045               2667.0
6            2072.166667           846.532978               2667.0
9            1859.750000           811.312979               2667.0
12           1691.200000           797.318678               2667.0

    qty_rolling_min_12m  qty_rolling_sum_12m  qty_expanding_mean  \
0                2667.0               2667.0         2667.000000
3                2446.5               5113.5         2556.750000
6                1103.0               6216.5         2072.166667
9                1103.0               7439.0         1859.750000
12               1017.0               8456.0         1691.200000

    qty_expanding_std  qty_expanding_max  qty_expanding_min  \
0         1740.059693             2667.0             2667.0
3          155.917045             2667.0             2446.5
6          846.532978             2667.0             1103.0
9          811.312979             2667.0             1103.0
12         797.318678             2667.0             1017.0

    monthly_seasonality  quarterly_seasonality  dow_seasonality  temp_lag_1m  \
0           7434.368421            4631.123077      4106.321429     0.000000
3           4061.217391            4631.123077      4773.453488    27.991643
6           2885.304348            4631.123077      3595.895349    27.343284
9           2344.173913            2819.217391      4106.321429    25.694986
12          2736.217391            2819.217391      5158.414286    24.534600

    humidity_lag_1m  wind_lag_1m  temp_lag_2m  humidity_lag_2m  wind_lag_2m  \
0          0.000000     0.000000     0.000000         0.000000     0.000000
3         49.857939    10.715181     0.000000         0.000000     0.000000
6         68.128901    12.634783    27.991643        49.857939    10.715181
9         78.798050    19.437744    27.343284        68.128901    12.634783
12        80.464043    22.617910    25.694986        78.798050    19.437744

    temp_lag_3m  humidity_lag_3m  wind_lag_3m  temp_lag_6m  humidity_lag_6m  \
0      0.000000         0.000000     0.000000          0.0              0.0
3      0.000000         0.000000     0.000000          0.0              0.0
6      0.000000         0.000000     0.000000          0.0              0.0
9     27.991643        49.857939    10.715181          0.0              0.0
12    27.343284        68.128901    12.634783          0.0              0.0

    wind_lag_6m  trends_lag_1m  trends_lag_2m  trends_lag_3m  trends_lag_6m  \
0           0.0            0.0            0.0            0.0            0.0
3           0.0           71.0            0.0            0.0            0.0
6           0.0           66.0           71.0            0.0            0.0
9           0.0           58.0           66.0           71.0            0.0
12          0.0           38.0           58.0           66.0            0.0

    branch_encoded  temp_humidity_interaction  temp_wind_interaction  \
0                0                1395.605644             299.935528
3                0                1862.867859             345.476444
6                0                2024.714801             499.452554
9                0                1974.153098             554.921380
12               0                2068.083969             522.071053

    temp_range  humidity_range  wind_range  temp_deviation  \
0         16.0            87.0        46.4       -1.517627
3         17.0            82.0        40.7       -2.173943
6         13.0            64.0        38.9       -2.445067
9         11.0            62.0        41.0       -2.005176
12        11.0            62.0        46.4       -3.230404

    humidity_deviation  months_since_last_sale  sales_momentum_3m  \
0           -12.569413                1.018397           1.000000
3            -0.741631                0.985545           1.000000
6             3.961861                1.018397           1.000000
9            -0.970494                0.985545           0.855312
12            7.490167                1.018397           0.658802

    sales_momentum_6m  branch_market_share
0                 1.0             0.137808
3                 1.0             0.124100
6                 1.0             0.103704
9                 1.0             0.161450
12                1.0             0.138944

In [242]:
# Prepare the data using the fixed features
print("\nPreparing data with fixed features...")
print("=" * 50)

def prepare_ml_data_fixed(df, target_col='Qty'):
    """
    Prepare data for machine learning models with improved NaN handling
    """
    print("Preparing data for ML models...")
    
    # Remove rows with missing target values
    df_clean = df.dropna(subset=[target_col]).copy()
    print(f"  After removing missing target values: {len(df_clean)} samples")
    
    # Check for any remaining missing values
    missing_before = df_clean.isnull().sum().sum()
    print(f"  Missing values before cleaning: {missing_before}")
    
    # Fill any remaining missing values with appropriate strategies
    print("  Filling remaining missing values...")
    
    # Fill numerical columns with median
    numerical_cols = df_clean.select_dtypes(include=[np.number]).columns
    for col in numerical_cols:
        if col != target_col and df_clean[col].isnull().any():
            df_clean[col] = df_clean[col].fillna(df_clean[col].median())
            print(f"    Filled {col} with median: {df_clean[col].median():.2f}")
    
    # Fill categorical columns with mode
    categorical_cols = df_clean.select_dtypes(include=['object']).columns
    for col in categorical_cols:
        if df_clean[col].isnull().any():
            mode_val = df_clean[col].mode()[0] if not df_clean[col].mode().empty else 'Unknown'
            df_clean[col] = df_clean[col].fillna(mode_val)
            print(f"    Filled {col} with mode: {mode_val}")
    
    # Define feature columns (exclude target and non-predictive columns)
    exclude_cols = [target_col, 'Date', 'Year', 'Month', 'Week', 'Branch', 'Segment', 'Rating']
    feature_cols = [col for col in df_clean.columns if col not in exclude_cols]
    
    print(f"  Total features: {len(feature_cols)}")
    print(f"  Total samples: {len(df_clean)}")
    
    # Check final missing values
    missing_after = df_clean.isnull().sum().sum()
    print(f"  Missing values after cleaning: {missing_after}")
    
    if missing_after > 0:
        print("  Warning: Still have missing values!")
        missing_cols = df_clean.columns[df_clean.isnull().any()].tolist()
        print(f"  Columns with missing values: {missing_cols}")
    
    # Sort by date
    df_clean_sorted = df_clean.sort_values('Date')
    df_clean_sorted =df_clean_sorted[df_clean_sorted['Date'] >= '2024-04-01']
    return df_clean_sorted[feature_cols]

# Prepare the data using the fixed features
ml_data_fixed = prepare_ml_data_fixed(ml_df_fixed)

Preparing data with fixed features...
==================================================
Preparing data for ML models...
  After removing missing target values: 275 samples
  Missing values before cleaning: 0
  Filling remaining missing values...
  Total features: 87
  Total samples: 275
  Missing values after cleaning: 0

In [243]:

ml_data_fixed

,Min Temp,Max Temp,Avg Temp,Min Humidity,Max Humidity,Avg Humidity,Min Wind Speed,Max Wind Speed,Avg Wind Speed,Interest,Seasonality_Level,year,month,day,dayofweek,dayofyear,week,quarter,month_sin,month_cos,dayofweek_sin,dayofweek_cos,quarter_sin,quarter_cos,qty_lag_1m,qty_lag_1m_mean,qty_lag_2m,qty_lag_2m_mean,qty_lag_3m,qty_lag_3m_mean,qty_lag_6m,qty_lag_12m,qty_rolling_mean_2m,qty_rolling_std_2m,qty_rolling_max_2m,qty_rolling_min_2m,qty_rolling_sum_2m,qty_rolling_mean_3m,qty_rolling_std_3m,qty_rolling_max_3m,qty_rolling_min_3m,qty_rolling_sum_3m,qty_rolling_mean_6m,qty_rolling_std_6m,qty_rolling_max_6m,qty_rolling_min_6m,qty_rolling_sum_6m,qty_rolling_mean_12m,qty_rolling_std_12m,qty_rolling_max_12m,qty_rolling_min_12m,qty_rolling_sum_12m,qty_expanding_mean,qty_expanding_std,qty_expanding_max,qty_expanding_min,monthly_seasonality,quarterly_seasonality,dow_seasonality,temp_lag_1m,humidity_lag_1m,wind_lag_1m,temp_lag_2m,humidity_lag_2m,wind_lag_2m,temp_lag_3m,humidity_lag_3m,wind_lag_3m,temp_lag_6m,humidity_lag_6m,wind_lag_6m,trends_lag_1m,trends_lag_2m,trends_lag_3m,trends_lag_6m,branch_encoded,temp_humidity_interaction,temp_wind_interaction,temp_range,humidity_range,wind_range,temp_deviation,humidity_deviation,months_since_last_sale,sales_momentum_3m,sales_momentum_6m,branch_market_share
229,26.6,39.0,31.515278,31.0,92.0,72.612500,0.0,27.7,11.727083,92,3,2024,4,1,0,92,14,2,8.660254e-01,-5.000000e-01,0.000000,1.000000,1.224647e-16,-1.000000e+00,21649.0,21649.0,13451.0,11582.75,9714.5,11427.166667,5695.0,19518.5,12368.25,13124.962519,21649.0,3087.5,24736.5,12729.166667,9301.779565,21649.0,3087.5,38187.5,12078.166667,7186.639031,21649.0,3087.5,72469.0,9794.333333,5788.739804,21649.0,3087.5,117532.0,7987.691667,5073.079199,22719.0,1130.0,7434.368421,4631.123077,4106.321429,29.282661,72.563172,10.352957,27.790661,74.606322,9.481034,26.239785,77.649194,7.772581,29.112500,80.241935,8.637634,53.0,34.0,28.0,30.0,2,2288.403108,369.582289,12.4,61.0,27.7,2.006007,10.185148,1.018397,1.593598,1.512097,0.25
227,20.0,37.0,28.940000,11.0,94.0,42.493056,1.8,27.7,11.957361,92,3,2024,4,1,0,92,14,2,8.660254e-01,-5.000000e-01,0.000000,1.000000,1.224647e-16,-1.000000e+00,7137.0,7137.0,4024.0,4174.50,4325.0,3418.500000,2246.0,3119.0,5112.25,2863.428910,7137.0,3087.5,10224.5,4749.500000,2119.994163,7137.0,3087.5,14248.5,4084.000000,1617.523323,7137.0,2646.5,24504.0,3139.416667,1516.007553,7137.0,1309.5,37673.0,2257.841667,1263.103762,7137.0,375.0,7434.368421,4631.123077,4106.321429,26.820565,45.533602,11.629032,23.902299,55.979885,12.298420,21.848118,66.743280,11.909543,24.041129,68.670699,10.454032,53.0,34.0,28.0,30.0,0,1229.749028,346.046031,17.0,83.0,25.9,-0.569270,-19.934296,1.018397,2.103558,1.808807,0.25
228,25.0,38.0,30.990278,31.0,100.0,75.025000,1.8,30.0,7.883194,92,3,2024,4,1,0,92,14,2,8.660254e-01,-5.000000e-01,0.000000,1.000000,1.224647e-16,-1.000000e+00,10894.5,10894.5,5498.0,3988.25,2478.5,3429.666667,1323.5,3579.0,6991.00,5520.382641,10894.5,3087.5,13982.0,6493.333333,3997.540317,10894.5,3087.5,19480.0,4961.500000,3227.671932,10894.5,2373.5,29769.0,3595.750000,2692.647198,10894.5,1062.5,43149.0,2121.843137,1764.377470,10894.5,22.0,7434.368421,4631.123077,4106.321429,30.036828,72.215054,8.187769,28.926580,69.438218,6.952730,27.837500,74.525538,6.379973,27.596371,84.411290,6.522177,53.0,34.0,28.0,30.0,1,2325.045590,244.302386,13.0,69.0,28.2,1.481007,12.597648,1.018397,3.060233,2.338297,0.25
230,23.0,41.0,31.690833,14.0,83.0,42.745833,1.8,27.7,11.929306,92,3,2024,4,1,0,92,14,2,8.660254e-01,-5.000000e-01,0.000000,1.000000,1.224647e-16,-1.000000e+00,22408.0,22408.0,12797.5,9591.25,6385.0,11939.000000,6570.5,7147.5,12747.75,13661.656566,22408.0,3087.5,25495.5,12764.333333,9660.292702,22408.0,3087.5,38293.0,12351.666667,8776.567630,23411.0,3087.5,74110.0,8670.333333,7194.089665,23411.0,1841.5,104044.0,5997.475000,5090.909762,23411.0,1307.0,7434.368421,4631.123077,4106.321429,28.688844,50.551075,11.830914,25.637931,57.461207,12.686638,22.811694,66.047043,11.617742,26.075000,64.655914,11.402016,53.0,34.0,28.0,30.0,3,1354.651080,378.049634,18.0,69.0,25.9,2.181563,-19.681518,1.018397,2.128285,2.059478,0.25
231,20.0,37.0,26.668011,18.0,100.0,67.383065,1.8,44.6,12.499731,100,2,2024,5,1,2,122,18,2,5.000000e-01,-8.660254e-01,0.974928,-0.222521,1.224647e-16,-1.000000e+00,3087.5,3087.5,7137.0,5580.50,4024.0,3877.666667,2646.5,2624.0,3087.50,0.000000,3087.5,3087.5,6175.0,4437.333333,2337.979915,7137.0,3087.5,13312.0,4157.500000,1547.649896,7137.0,3087.5,24945.0,3178.041667,1507.562941,7137.0,1309.5,38136.5,2271.442623,1257.030128,7137.0,375.0,4061.217391,4631.123077,4773.453488,28.940000,42.493056,11.957361,26.820565,45.533602,11.629032,23.902299,55.979885,12.298420,22.469444,79.108333,11.598194,92.0,53.0,34.0,26.0,0,1796.972289,333.342966,17.0,82.0,42.8,-2.849216,-1.487468,0.985545,1.953531,1.830335,0.25
234,22.0,42.0,30.941129,10.0,94.0,56.587366,1.8,33.5,14.042473,100,2,2024,5,1,2,122,18,2,5.000000e-01,-8.660254e-01,0.974928,-0.222521,1.224647e-16,-1.000000e+00,3087.5,3087.5,22408.0,17602.75,12797.5,14197.833333,6021.0,7890.5,3087.50,0.000000,3087.5,3087.5,6175.0,9527.666667,11154.695876,22408.0,3087.5,28583.0,11862.750000,9267.727913,23411.0,3087.5,71176.5,8270.083333,7372.810457,23411.0,1841.5,99241.0,5949.770492,5062.037643,23411.0,1307.0,4061.217391,4631.123077,4773.453488,31.690833,42.745833,11.929306,28.688844,50.551075,11.830914,25.637931,57.461207,12.686638,24.226806,74.088889,12.074444,92.0,53.0,34.0,26.0,3,1750.876980,434.489973,20.0,84.0,31.7,1.423903,-12.283166,0.985545,1.601350,1.993816,0.25
233,26.0,41.0,32.576344,30.0,96.0,71.341398,0.0,29.5,12.446774,100,2,2024,5,1,2,122,18,2,5.000000e-01,-8.660254e-01,0.974928,-0.222521,1.224647e-16,-1.000000e+00,3087.5,3087.5,21649.0,17550.00,13451.0,13901.333333,6028.5,13518.0,3087.50,0.000000,3087.5,3087.5,6175.0,9274.666667,10716.487022,21649.0,3087.5,27824.0,11588.000000,7759.264695,21649.0,3087.5,69528.0,8925.125000,5959.364183,21649.0,3087.5,107101.5,7907.360656,5069.599034,22719.0,1130.0,4061.217391,4631.123077,4773.453488,31.515278,72.612500,11.727083,29.282661,72.563172,10.352957,27.790661,74.606322,9.481034,27.096389,86.715278,7.903333,92.0,53.0,34.0,26.0,2,2324.041924,405.470399,15.0,66.0,29.5,3.059118,2.470866,0.985545,1.172916,1.465470,0.25
232,23.8,38.0,28.547177,40.0,100.0,82.731183,2.0,26.0,7.585081,100,2,2024,5,1,2,122,18,2,5.000000e-01,-8.660254e-01,0.974928,-0.222521,1.224647e-16,-1.000000e+00,3087.5,3087.5,10894.5,8196.25,5498.0,4471.166667,2373.5,2365.0,3087.50,0.000000,3087.5,3087.5,6175.0,5689.833333,4507.373552,10894.5,3087.5,17069.5,5080.500000,3124.691873,10894.5,2478.5,30483.0,3655.958333,2670.612974,10894.5,1062.5,43871.5,2140.413462,1752.118904,10894.5,22.0,4061.217391,4631.123077,4773.453488,30.990278,75.025000,7.883194,30.036828,72.215054,8.187769,28.926580,69.438218,6.952730,27.974444,82.440278,6.045972,92.0,53.0,34.0,26.0,1,2361.741753,216.532643,14.2,60.0,24.0,-0.970049,13.860651,0.985545,2.658287,2.373607,0.25
236,23.1,34.0,27.325972,56.0,100.0,87.202778,2.0,28.0,6.930694,68,1,2024,6,1,5,153,22,2,1.224647e-16,-1.000000e+00,-0.974928,-0.222521,1.224647e-16,-1.000000e+00,3087.5,3087.5,3087.5,6991.00,10894.5,6290.333333,5437.0,1062.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,4688.916667,3216.937308,10894.5,2478.5,28133.5,3824.708333,2553.238767,10894.5,1323.5,45896.5,2158.283019,1740.059693,10894.5,22.0,2885.304348,4631.123077,3595.895349,28.547177,82.731183,7.585081,30.990278,75.025000,7.883194,30.036828,72.215054,8.187769,28.412231,76.419355,6.504435,100.0,92.0,53.0,27.0,1,2382.900683,189.387964,10.9,44.0,26.0,-0.814081,12.366589,1.018397,1.430535,2.172522,0.25
235,20.0,33.0,24.359722,46.0,100.0,76.313889,3.6,37.1,17.525694,68,1,2024,6,1,5,153,22,2,1.224647e-16,-1.000000e+00,-0.974928,-0.222521,1.224647e-16,-1.000000e+00,3087.5,3087.5,3087.5,5112.25,7137.0,5162.000000,3284.0,1880.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,4124.750000,1571.722837,7137.0,3087.5,24748.5,3278.625000,1452.376910,7137.0,1309.5,39343.5,2284.604839,1250.984485,7137.0,375.0,2885.304348,4631.123077,3595.895349,26.668011,67.383065,12.499731,28.940000,42.493056,11.957361,26.820565,45.533602,11.629032,21.308737,76.924731,12.026882,100.0,92.0,53.0,27.0,0,1858.985135,426.921048,13.0,54.0,33.5,-3.780331,1.477700,1.018397,1.351437,1.805454,0.25
238,23.0,39.0,27.681111,30.0,94.0,72.966667,1.8,29.5,16.512361,68,1,2024,6,1,5,153,22,2,1.224647e-16,-1.000000e+00,-0.974928,-0.222521,1.224647e-16,-1.000000e+00,3087.5,3087.5,3087.5,12747.75,22408.0,13863.500000,23411.0,4617.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,8475.500000,7800.718717,22408.0,3087.5,50853.0,8142.583333,7454.494705,23411.0,1841.5,97711.0,5903.604839,5033.517102,23411.0,1307.0,2885.304348,4631.123077,3595.895349,30.941129,56.587366,14.042473,31.690833,42.745833,11.929306,28.688844,50.551075,11.830914,21.464919,70.818548,11.647581,100.0,92.0,53.0,27.0,3,2019.798407,457.080503,16.0,64.0,27.7,-0.458942,-1.869522,1.018397,0.522986,1.435648,0.25
237,24.0,39.0,30.924306,37.0,100.0,73.879167,0.0,37.1,12.794861,68,1,2024,6,1,5,153,22,2,1.224647e-16,-1.000000e+00,-0.974928,-0.222521,1.224647e-16,-1.000000e+00,3087.5,3087.5,3087.5,12368.25,21649.0,14938.166667,18538.5,6393.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,9012.833333,7552.365098,21649.0,3087.5,54077.0,8649.625000,6160.078022,21649.0,3087.5,103795.5,7829.620968,5064.997895,22719.0,1130.0,2885.304348,4631.123077,3595.895349,32.576344,71.341398,12.446774,31.515278,72.612500,11.727083,29.282661,72.563172,10.352957,26.423522,82.145161,10.311425,100.0,92.0,53.0,27.0,2,2284.661924,395.672195,15.0,63.0,37.1,2.784253,-0.957022,1.018397,0.394336,1.151120,0.25
242,21.0,32.0,25.463710,56.0,94.0,82.231183,5.4,38.9,20.763038,44,1,2024,7,1,0,183,27,3,-5.000000e-01,-8.660254e-01,0.000000,1.000000,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,12764.333333,6385.0,1841.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,7925.916667,8088.314598,22408.0,3087.5,47555.5,8246.416667,7366.911555,23411.0,3087.5,98957.0,5858.904762,5005.349599,23411.0,1307.0,2344.173913,2819.217391,4106.321429,27.681111,72.966667,16.512361,30.941129,56.587366,14.042473,31.690833,42.745833,11.929306,22.811694,66.047043,11.617742,68.0,100.0,92.0,28.0,3,2093.910965,528.703962,11.0,38.0,33.5,-1.076066,0.796645,0.985545,0.526976,1.352798,0.25
241,24.0,37.0,30.626747,38.0,100.0,72.650538,0.0,33.5,13.285484,44,1,2024,7,1,0,183,27,3,-5.000000e-01,-8.660254e-01,0.000000,1.000000,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,12729.166667,9714.5,5127.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,7908.333333,7905.552610,21649.0,3087.5,47450.0,8479.625000,6292.833179,21649.0,3087.5,101755.5,7754.349206,5059.384745,22719.0,1130.0,2344.173913,2819.217391,4106.321429,30.924306,73.879167,12.794861,32.576344,71.341398,12.446774,31.515278,72.612500,11.727083,26.239785,77.649194,7.772581,68.0,100.0,92.0,28.0,2,2225.049658,406.891157,13.0,62.0,33.5,4.086971,-8.784000,0.985545,0.398164,1.019858,0.25
239,20.0,31.0,23.513441,51.0,94.0,78.372312,7.6,41.0,22.128898,44,1,2024,7,1,0,183,27,3,-5.000000e-01,-8.660254e-01,0.000000,1.000000,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,4749.500000,4325.0,1309.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3918.500000,1620.624355,7137.0,3087.5,23511.0,3426.791667,1317.677734,7137.0,2246.0,41121.5,2297.349206,1244.971183,7137.0,375.0,2344.173913,2819.217391,4106.321429,24.359722,76.313889,17.525694,26.668011,67.383065,12.499731,28.940000,42.493056,11.957361,21.848118,66.743280,11.909543,68.0,100.0,92.0,28.0,0,1842.802719,520.326531,11.0,43.0,33.4,-3.026335,-3.062226,0.985545,1.343940,1.705661,0.25
240,23.0,32.0,26.135618,59.0,100.0,88.801075,2.0,32.0,7.522984,44,1,2024,7,1,0,183,27,3,-5.000000e-01,-8.660254e-01,0.000000,1.000000,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,6493.333333,2478.5,2035.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,4790.416667,3141.980529,10894.5,3087.5,28742.5,3912.375000,2503.802464,10894.5,1323.5,46948.5,2175.490741,1728.198193,10894.5,22.0,2344.173913,2819.217391,4106.321429,27.325972,87.202778,6.930694,28.547177,82.731183,7.585081,30.990278,75.025000,7.883194,27.837500,74.525538,6.379973,68.0,100.0,92.0,28.0,1,2320.871006,196.617835,9.0,41.0,30.0,-0.404158,7.366538,0.985545,1.419220,2.201994,0.25
244,23.0,33.0,26.667620,59.0,100.0,86.250000,1.4,30.0,7.760392,38,1,2024,8,1,3,214,31,3,-8.660254e-01,-5.000000e-01,0.433884,-0.900969,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,5689.833333,5498.0,3915.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,4388.666667,3187.194404,10894.5,3087.5,26332.0,3843.416667,2515.093409,10894.5,1323.5,46121.0,2192.072727,1716.532329,10894.5,22.0,2736.217391,2819.217391,5158.414286,26.135618,88.801075,7.522984,27.325972,87.202778,6.930694,28.547177,82.731183,7.585081,28.926580,69.438218,6.952730,44.0,68.0,100.0,34.0,1,2300.082267,206.951177,10.0,41.0,28.6,0.018863,5.429776,1.018397,1.408484,2.002063,0.25
245,23.5,38.0,30.322581,40.0,98.0,76.190860,0.0,27.7,12.188038,38,1,2024,8,1,3,214,31,3,-8.660254e-01,-5.000000e-01,0.433884,-0.900969,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,9274.666667,13451.0,6382.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,6181.083333,7577.700643,21649.0,3087.5,37086.5,8205.041667,6462.265084,21649.0,3087.5,98460.5,7681.429688,5052.857694,22719.0,1130.0,2736.217391,2819.217391,5158.414286,30.626747,72.650538,13.285484,30.924306,73.879167,12.794861,32.576344,71.341398,12.446774,27.790661,74.606322,9.481034,44.0,68.0,100.0,34.0,2,2310.303503,369.572754,14.5,58.0,27.7,3.673823,-4.629364,1.018397,0.401943,0.804679,0.25
246,21.0,34.0,25.889373,56.0,100.0,82.211172,3.6,206.0,15.790599,38,1,2024,8,1,3,214,31,3,-8.660254e-01,-5.000000e-01,0.433884,-0.900969,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,9527.666667,12797.5,4275.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,6307.583333,7887.561096,22408.0,3087.5,37845.5,8147.458333,7432.789775,23411.0,3087.5,97769.5,5815.601562,4977.535566,23411.0,1307.0,2736.217391,2819.217391,5158.414286,25.463710,82.231183,20.763038,27.681111,72.966667,16.512361,30.941129,56.587366,14.042473,25.637931,57.461207,12.686638,44.0,68.0,100.0,34.0,3,2128.395712,408.808724,13.0,44.0,202.4,-0.759385,1.390948,1.018397,0.530900,1.084597,0.25
243,20.0,31.0,23.981183,49.0,100.0,79.168011,1.8,38.9,15.098118,38,1,2024,8,1,3,214,31,3,-8.660254e-01,-5.000000e-01,0.433884,-0.900969,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,4437.333333,4024.0,2268.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3762.416667,1653.201452,7137.0,3087.5,22574.5,3495.083333,1272.627076,7137.0,2246.0,41941.0,2309.695312,1238.993987,7137.0,375.0,2736.217391,2819.217391,5158.414286,23.513441,78.372312,22.128898,24.359722,76.313889,17.525694,26.668011,67.383065,12.499731,23.902299,55.979885,12.298420,44.0,68.0,100.0,34.0,0,1898.542537,362.070734,11.0,51.0,37.1,-2.667575,-1.652213,1.018397,1.336756,1.628967,0.25
250,21.0,34.0,25.093305,46.0,100.0,83.463040,1.8,33.5,15.950767,36,1,2024,9,1,6,245,35,3,-1.000000e+00,-1.836970e-16,-0.781831,0.623490,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,22408.0,4739.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,8009.833333,7516.456519,23411.0,3087.5,96118.0,5773.630769,4950.074553,23411.0,1307.0,3377.260870,2819.217391,3543.118421,25.889373,82.211172,15.790599,25.463710,82.231183,20.763038,27.681111,72.966667,16.512361,28.688844,50.551075,11.830914,38.0,44.0,68.0,53.0,3,2094.363567,400.257470,13.0,54.0,31.7,-1.224086,1.281163,1.018397,0.534759,0.534759,0.25
249,23.4,38.6,30.490278,34.0,100.0,74.261111,0.0,31.7,10.915417,36,1,2024,9,1,6,245,35,3,-1.000000e+00,-1.836970e-16,-0.781831,0.623490,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,21649.0,7946.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,7800.125000,6629.990190,21649.0,3087.5,93601.5,7610.753846,5045.505232,22719.0,1130.0,3377.260870,2819.217391,3543.118421,30.322581,76.190860,12.188038,30.626747,72.650538,13.285484,30.924306,73.879167,12.794861,29.282661,72.563172,10.352957,38.0,44.0,68.0,53.0,2,2264.241906,332.814086,15.2,66.0,31.7,4.172887,-7.920767,1.018397,0.405676,0.405676,0.25
247,19.0,30.0,23.947917,37.0,95.0,74.143056,3.6,40.7,17.759861,36,1,2024,9,1,6,245,35,3,-1.000000e+00,-1.836970e-16,-0.781831,0.623490,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,7137.0,2841.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3515.625000,1263.063090,7137.0,2246.0,42187.5,2321.661538,1233.056144,7137.0,375.0,3377.260870,2819.217391,3543.118421,23.981183,79.168011,15.098118,23.513441,78.372312,22.128898,24.359722,76.313889,17.525694,26.820565,45.533602,11.629032,38.0,44.0,68.0,53.0,0,1775.571716,425.311674,11.0,58.0,37.1,-2.369475,-8.038822,1.018397,1.329867,1.329867,0.25
248,22.8,34.0,27.373112,53.0,100.0,83.048338,1.8,26.0,7.966767,36,1,2024,9,1,6,245,35,3,-1.000000e+00,-1.836970e-16,-0.781831,0.623490,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,10894.5,2678.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3877.500000,2500.601428,10894.5,1323.5,46530.0,2208.062500,1705.059674,10894.5,22.0,3377.260870,2819.217391,3543.118421,26.667620,86.250000,7.760392,26.135618,88.801075,7.522984,27.325972,87.202778,6.930694,30.036828,72.215054,8.187769,38.0,44.0,68.0,53.0,1,2273.291450,218.075214,11.2,47.0,24.2,1.055721,0.866461,1.018397,1.398285,1.398285,0.25
251,18.0,31.0,23.466398,37.0,100.0,79.661290,1.8,27.7,9.784140,33,1,2024,10,1,1,275,40,4,-8.660254e-01,5.000000e-01,0.781831,0.623490,-2.449294e-16,1.000000e+00,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,3087.5,2246.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3585.750000,1208.340156,7137.0,2646.5,43029.0,2333.265152,1227.160444,7137.0,375.0,2796.326087,4429.753623,3893.842857,23.947917,74.143056,17.759861,23.981183,79.168011,15.098118,23.513441,78.372312,22.128898,28.940000,42.493056,11.957361,36.0,38.0,44.0,92.0,0,1869.363532,229.598517,13.0,63.0,25.9,-2.554285,-1.327339,0.985545,1.323253,1.323253,0.25
253,23.8,36.8,29.207527,40.0,100.0,81.030914,0.0,27.7,8.559409,33,1,2024,10,1,1,275,40,4,-8.660254e-01,5.000000e-01,0.781831,0.623490,-2.449294e-16,1.000000e+00,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,3087.5,5695.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,7582.833333,6746.953280,21649.0,3087.5,90994.0,7542.219697,5037.407305,22719.0,1130.0,2796.326087,4429.753623,3893.842857,30.490278,74.261111,10.915417,30.322581,76.190860,12.188038,30.626747,72.650538,13.285484,31.515278,72.612500,11.727083,36.0,38.0,44.0,92.0,2,2366.712598,249.999157,13.0,60.0,27.7,3.186845,0.042285,0.985545,0.409362,0.409362,0.25

In [244]:
# loaded_model.predict(test)
result = xgb_baseline_model.predict(ml_data_fixed)

In [249]:
ml_df_fixed[ml_df_fixed['Date'] >= '2024-04-01']['Qty'] = result

In [252]:
result

array([5003.3804, 6317.7183, 5413.4175, 6762.5317, 3494.7158, 3568.3992,
       3935.6848, 3690.0425, 3129.4365, 2827.0742, 3202.3086, 3386.3994,
       3097.7437, 3393.9915, 2812.8206, 3189.311 , 3280.4482, 3463.3752,
       3261.4336, 2742.624 , 3524.2114, 3607.0657, 3122.389 , 3473.317 ,
       3044.916 , 3606.908 , 3542.4949, 3401.7659, 3241.619 , 3317.3525,
       3324.2659, 3148.357 , 3771.07  , 4623.427 , 4055.5774, 3959.466 ,
       3626.4443, 3890.1995, 3679.5957, 3419.396 , 3358.3296, 3491.9272,
       3415.0852, 3604.2134, 3637.041 , 3311.67  , 3702.7266, 3619.362 ],
      dtype=float32)

In [251]:
ml_df_fixed[ml_df_fixed['Date'] >= '2024-04-01']

,Date,Branch,Qty,Min Temp,Max Temp,Avg Temp,Min Humidity,Max Humidity,Avg Humidity,Min Wind Speed,Max Wind Speed,Avg Wind Speed,Interest,Seasonality_Level,year,month,day,dayofweek,dayofyear,week,quarter,month_sin,month_cos,dayofweek_sin,dayofweek_cos,quarter_sin,quarter_cos,qty_lag_1m,qty_lag_1m_mean,qty_lag_2m,qty_lag_2m_mean,qty_lag_3m,qty_lag_3m_mean,qty_lag_6m,qty_lag_12m,qty_rolling_mean_2m,qty_rolling_std_2m,qty_rolling_max_2m,qty_rolling_min_2m,qty_rolling_sum_2m,qty_rolling_mean_3m,qty_rolling_std_3m,qty_rolling_max_3m,qty_rolling_min_3m,qty_rolling_sum_3m,qty_rolling_mean_6m,qty_rolling_std_6m,qty_rolling_max_6m,qty_rolling_min_6m,qty_rolling_sum_6m,qty_rolling_mean_12m,qty_rolling_std_12m,qty_rolling_max_12m,qty_rolling_min_12m,qty_rolling_sum_12m,qty_expanding_mean,qty_expanding_std,qty_expanding_max,qty_expanding_min,monthly_seasonality,quarterly_seasonality,dow_seasonality,temp_lag_1m,humidity_lag_1m,wind_lag_1m,temp_lag_2m,humidity_lag_2m,wind_lag_2m,temp_lag_3m,humidity_lag_3m,wind_lag_3m,temp_lag_6m,humidity_lag_6m,wind_lag_6m,trends_lag_1m,trends_lag_2m,trends_lag_3m,trends_lag_6m,branch_encoded,temp_humidity_interaction,temp_wind_interaction,temp_range,humidity_range,wind_range,temp_deviation,humidity_deviation,months_since_last_sale,sales_momentum_3m,sales_momentum_6m,branch_market_share
227,2024-04-01,BLR,3087.5,20.0,37.0,28.940000,11.0,94.0,42.493056,1.8,27.7,11.957361,92,3,2024,4,1,0,92,14,2,8.660254e-01,-5.000000e-01,0.000000,1.000000,1.224647e-16,-1.000000e+00,7137.0,7137.0,4024.0,4174.50,4325.0,3418.500000,2246.0,3119.0,5112.25,2863.428910,7137.0,3087.5,10224.5,4749.500000,2119.994163,7137.0,3087.5,14248.5,4084.000000,1617.523323,7137.0,2646.5,24504.0,3139.416667,1516.007553,7137.0,1309.5,37673.0,2257.841667,1263.103762,7137.0,375.0,7434.368421,4631.123077,4106.321429,26.820565,45.533602,11.629032,23.902299,55.979885,12.298420,21.848118,66.743280,11.909543,24.041129,68.670699,10.454032,53.0,34.0,28.0,30.0,0,1229.749028,346.046031,17.0,83.0,25.9,-0.569270,-19.934296,1.018397,2.103558,1.808807,0.25
231,2024-05-01,BLR,3087.5,20.0,37.0,26.668011,18.0,100.0,67.383065,1.8,44.6,12.499731,100,2,2024,5,1,2,122,18,2,5.000000e-01,-8.660254e-01,0.974928,-0.222521,1.224647e-16,-1.000000e+00,3087.5,3087.5,7137.0,5580.50,4024.0,3877.666667,2646.5,2624.0,3087.50,0.000000,3087.5,3087.5,6175.0,4437.333333,2337.979915,7137.0,3087.5,13312.0,4157.500000,1547.649896,7137.0,3087.5,24945.0,3178.041667,1507.562941,7137.0,1309.5,38136.5,2271.442623,1257.030128,7137.0,375.0,4061.217391,4631.123077,4773.453488,28.940000,42.493056,11.957361,26.820565,45.533602,11.629032,23.902299,55.979885,12.298420,22.469444,79.108333,11.598194,92.0,53.0,34.0,26.0,0,1796.972289,333.342966,17.0,82.0,42.8,-2.849216,-1.487468,0.985545,1.953531,1.830335,0.25
235,2024-06-01,BLR,3087.5,20.0,33.0,24.359722,46.0,100.0,76.313889,3.6,37.1,17.525694,68,1,2024,6,1,5,153,22,2,1.224647e-16,-1.000000e+00,-0.974928,-0.222521,1.224647e-16,-1.000000e+00,3087.5,3087.5,3087.5,5112.25,7137.0,5162.000000,3284.0,1880.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,4124.750000,1571.722837,7137.0,3087.5,24748.5,3278.625000,1452.376910,7137.0,1309.5,39343.5,2284.604839,1250.984485,7137.0,375.0,2885.304348,4631.123077,3595.895349,26.668011,67.383065,12.499731,28.940000,42.493056,11.957361,26.820565,45.533602,11.629032,21.308737,76.924731,12.026882,100.0,92.0,53.0,27.0,0,1858.985135,426.921048,13.0,54.0,33.5,-3.780331,1.477700,1.018397,1.351437,1.805454,0.25
239,2024-07-01,BLR,3087.5,20.0,31.0,23.513441,51.0,94.0,78.372312,7.6,41.0,22.128898,44,1,2024,7,1,0,183,27,3,-5.000000e-01,-8.660254e-01,0.000000,1.000000,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,4749.500000,4325.0,1309.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3918.500000,1620.624355,7137.0,3087.5,23511.0,3426.791667,1317.677734,7137.0,2246.0,41121.5,2297.349206,1244.971183,7137.0,375.0,2344.173913,2819.217391,4106.321429,24.359722,76.313889,17.525694,26.668011,67.383065,12.499731,28.940000,42.493056,11.957361,21.848118,66.743280,11.909543,68.0,100.0,92.0,28.0,0,1842.802719,520.326531,11.0,43.0,33.4,-3.026335,-3.062226,0.985545,1.343940,1.705661,0.25
243,2024-08-01,BLR,3087.5,20.0,31.0,23.981183,49.0,100.0,79.168011,1.8,38.9,15.098118,38,1,2024,8,1,3,214,31,3,-8.660254e-01,-5.000000e-01,0.433884,-0.900969,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,4437.333333,4024.0,2268.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3762.416667,1653.201452,7137.0,3087.5,22574.5,3495.083333,1272.627076,7137.0,2246.0,41941.0,2309.695312,1238.993987,7137.0,375.0,2736.217391,2819.217391,5158.414286,23.513441,78.372312,22.128898,24.359722,76.313889,17.525694,26.668011,67.383065,12.499731,23.902299,55.979885,12.298420,44.0,68.0,100.0,34.0,0,1898.542537,362.070734,11.0,51.0,37.1,-2.667575,-1.652213,1.018397,1.336756,1.628967,0.25
247,2024-09-01,BLR,3087.5,19.0,30.0,23.947917,37.0,95.0,74.143056,3.6,40.7,17.759861,36,1,2024,9,1,6,245,35,3,-1.000000e+00,-1.836970e-16,-0.781831,0.623490,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,7137.0,2841.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3515.625000,1263.063090,7137.0,2246.0,42187.5,2321.661538,1233.056144,7137.0,375.0,3377.260870,2819.217391,3543.118421,23.981183,79.168011,15.098118,23.513441,78.372312,22.128898,24.359722,76.313889,17.525694,26.820565,45.533602,11.629032,38.0,44.0,68.0,53.0,0,1775.571716,425.311674,11.0,58.0,37.1,-2.369475,-8.038822,1.018397,1.329867,1.329867,0.25
251,2024-10-01,BLR,3087.5,18.0,31.0,23.466398,37.0,100.0,79.661290,1.8,27.7,9.784140,33,1,2024,10,1,1,275,40,4,-8.660254e-01,5.000000e-01,0.781831,0.623490,-2.449294e-16,1.000000e+00,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,3087.5,2246.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3585.750000,1208.340156,7137.0,2646.5,43029.0,2333.265152,1227.160444,7137.0,375.0,2796.326087,4429.753623,3893.842857,23.947917,74.143056,17.759861,23.981183,79.168011,15.098118,23.513441,78.372312,22.128898,28.940000,42.493056,11.957361,36.0,38.0,44.0,92.0,0,1869.363532,229.598517,13.0,63.0,25.9,-2.554285,-1.327339,0.985545,1.323253,1.323253,0.25
255,2024-11-01,BLR,3087.5,16.0,28.0,21.892639,36.0,100.0,77.916667,3.6,27.7,11.589583,28,1,2024,11,1,4,306,44,4,-5.000000e-01,8.660254e-01,-0.433884,-0.900969,-2.449294e-16,1.000000e+00,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,3087.5,2646.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3622.500000,1183.630816,7137.0,3087.5,43470.0,2344.522388,1221.309275,7137.0,375.0,2838.673913,4429.753623,6021.269231,23.466398,79.661290,9.784140,23.947917,74.143056,17.759861,23.981183,79.168011,15.098118,26.668011,67.383065,12.499731,33.0,36.0,38.0,100.0,0,1705.801447,253.726563,12.0,64.0,24.1,-2.977480,-3.594337,1.018397,1.316899,1.316899,0.25
259,2024-12-01,BLR,3087.5,14.0,28.0,21.342742,35.0,100.0,80.017473,3.6,25.9,11.776478,26,3,2024,12,1,6,336,48,4,-2.449294e-16,1.000000e+00,-0.781831,0.623490,-2.449294e-16,1.000000e+00,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,3087.5,3284.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3606.125000,1190.081207,7137.0,3087.5,43273.5,2355.448529,1215.504665,7137.0,375.0,7654.260870,4429.753623,3543.118421,21.892639,77.916667,11.589583,23.466398,79.661290,9.784140,23.947917,74.143056,17.759861,24.359722,76.313889,17.525694,28.0,33.0,36.0,68.0,0,1707.792279,251.342341,14.0,65.0,22.3,-2.665977,1.112724,0.985545,1.310791,1.310791,0.25
263,2025-01-01,BLR,3087.5,12.0,31.0,20.597581,13.0,100.0,68.731183,1.8,25.9,12.004167,30,2,2025,1,1,2,1,1,1,5.000000e-01,8.660254e-01,0.974928,-0.222521,1.000000e+00,6.123234e-17,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,3087.5,4325.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3503.000000,1175.654537,7137.0,3087.5,42036.0,2366.057971,1209.748329,7137.0,375.0,3915.062500,5797.812500,4773.453488,21.342742,80.017473,11.776478,21.892639,77.916667,11.589583,23.466398,79.661290,9.784140,23.513441,78.372312,22.128898,26.0,28.0,33.0,44.0,0,1415.696080,247.256791,19.0,87.0,24.1,-3.708619,-3.882132,1.018397,1.304913,1.304913,0.25
267,2025-02-01,BLR,3087.5,12.0,32.0,23.154762,8.0,100.0,50.306548,0.0,37.1,12.213393,40,3,2025,2,1,5,32,5,1,8.660254e-01,5.000000e-01,-0.974928,-0.222521,1.000000e+00,6.123234e-17,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,3087.5,4024.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3424.958333,1168.989958,7137.0,3087.5,41099.5,2376.364286,1204.041699,7137.0,375.0,6437.520833,5797.812500,3595.895349,20.597581,68.731183,12.004167,21.342742,80.017473,11.776478,21.892639,77.916667,11.589583,23.981183,79.168011,15.098118,30.0,26.0,28.0,38.0,0,1164.836132,282.798204,20.0,92.0,37.1,-2.429975,-13.798957,1.018397,1.299254,1.299254,0.25
271,2025-03-01,BLR,3087.5,16.0,35.0,25.794624,11.0,98.0,50.341398,0.0,33.5,11.462769,65,3,2025,3,1,5,60,9,1,1.000000e+00,6.123234e-17,-0.974928,-0.222521,1.000000e+00,6.123234e-17,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,3087.5,7137.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3087.500000,0.000000,3087.5,3087.5,37050.0,2386.380282,1198.385961,7137.0,375.0,7040.854167,5797.812500,3595.895349,23.154762,50.306548,12.213393,20.597581,68.731183,12.004167,21.342742,80.017473,11.776478,23.947917,74.143056,17.759861,40.0,30.0,26.0,36.0,0,1298.537412,295.677808,19.0,87.0,33.5,-2.039671,-11.505834,0.919842,1.293800,1.293800,0.25
228,2024-04-01,COK,3087.5,25.0,38.0,30.990278,31.0,100.0,75.025000,1.8,30.0,7.883194,92,3,2024,4,1,0,92,14,2,8.660254e-01,-5.000000e-01,0.000000,1.000000,1.224647e-16,-1.000000e+00,10894.5,10894.5,5498.0,3988.25,2478.5,3429.666667,1323.5,3579.0,6991.00,5520.382641,10894.5,3087.5,13982.0,6493.333333,3997.540317,10894.5,3087.5,19480.0,4961.500000,3227.671932,10894.5,2373.5,29769.0,3595.750000,2692.647198,10894.5,1062.5,43149.0,2121.843137,1764.377470,10894.5,22.0,7434.368421,4631.123077,4106.321429,30.036828,72.215054,8.187769,28.926580,69.438218,6.952730,27.837500,74.525538,6.379973,27.596371,84.411290,6.522177,53.0,34.0,28.0,30.0,1,2325.045590,244.302386,13.0,69.0,28.2,1.481007,12.597648,1.018397,3.060233,2.338297,0.25
232,2024-05-01,COK,3087.5,23.8,38.0,28.547177,40.0,100.0,82.731183,2.0,26.0,7.585081,100,2,2024,5,1,2,122,18,2,5.000000e-01,-8.660254e-01,0.974928,-0.222521,1.224647e-16,-1.000000e+00,3087.5,3087.5,10894.5,8196.25,5498.0,4471.166667,2373.5,2365.0,3087.50,0.000000,3087.5,3087.5,6175.0,5689.833333,4507.373552,10894.5,3087.5,17069.5,5080.500000,3124.691873,10894.5,2478.5,30483.0,3655.958333,2670.612974,10894.5,1062.5,43871.5,2140.413462,1752.118904,10894.5,22.0,4061.217391,4631.123077,4773.453488,30.990278,75.025000,7.883194,30.036828,72.215054,8.187769,28.926580,69.438218,6.952730,27.974444,82.440278,6.045972,92.0,53.0,34.0,26.0,1,2361.741753,216.532643,14.2,60.0,24.0,-0.970049,13.860651,0.985545,2.658287,2.373607,0.25
236,2024-06-01,COK,3087.5,23.1,34.0,27.325972,56.0,100.0,87.202778,2.0,28.0,6.930694,68,1,2024,6,1,5,153,22,2,1.224647e-16,-1.000000e+00,-0.974928,-0.222521,1.224647e-16,-1.000000e+00,3087.5,3087.5,3087.5,6991.00,10894.5,6290.333333,5437.0,1062.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,4688.916667,3216.937308,10894.5,2478.5,28133.5,3824.708333,2553.238767,10894.5,1323.5,45896.5,2158.283019,1740.059693,10894.5,22.0,2885.304348,4631.123077,3595.895349,28.547177,82.731183,7.585081,30.990278,75.025000,7.883194,30.036828,72.215054,8.187769,28.412231,76.419355,6.504435,100.0,92.0,53.0,27.0,1,2382.900683,189.387964,10.9,44.0,26.0,-0.814081,12.366589,1.018397,1.430535,2.172522,0.25
240,2024-07-01,COK,3087.5,23.0,32.0,26.135618,59.0,100.0,88.801075,2.0,32.0,7.522984,44,1,2024,7,1,0,183,27,3,-5.000000e-01,-8.660254e-01,0.000000,1.000000,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,6493.333333,2478.5,2035.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,4790.416667,3141.980529,10894.5,3087.5,28742.5,3912.375000,2503.802464,10894.5,1323.5,46948.5,2175.490741,1728.198193,10894.5,22.0,2344.173913,2819.217391,4106.321429,27.325972,87.202778,6.930694,28.547177,82.731183,7.585081,30.990278,75.025000,7.883194,27.837500,74.525538,6.379973,68.0,100.0,92.0,28.0,1,2320.871006,196.617835,9.0,41.0,30.0,-0.404158,7.366538,0.985545,1.419220,2.201994,0.25
244,2024-08-01,COK,3087.5,23.0,33.0,26.667620,59.0,100.0,86.250000,1.4,30.0,7.760392,38,1,2024,8,1,3,214,31,3,-8.660254e-01,-5.000000e-01,0.433884,-0.900969,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,5689.833333,5498.0,3915.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,4388.666667,3187.194404,10894.5,3087.5,26332.0,3843.416667,2515.093409,10894.5,1323.5,46121.0,2192.072727,1716.532329,10894.5,22.0,2736.217391,2819.217391,5158.414286,26.135618,88.801075,7.522984,27.325972,87.202778,6.930694,28.547177,82.731183,7.585081,28.926580,69.438218,6.952730,44.0,68.0,100.0,34.0,1,2300.082267,206.951177,10.0,41.0,28.6,0.018863,5.429776,1.018397,1.408484,2.002063,0.25
248,2024-09-01,COK,3087.5,22.8,34.0,27.373112,53.0,100.0,83.048338,1.8,26.0,7.966767,36,1,2024,9,1,6,245,35,3,-1.000000e+00,-1.836970e-16,-0.781831,0.623490,-1.000000e+00,-1.836970e-16,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,10894.5,2678.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3877.500000,2500.601428,10894.5,1323.5,46530.0,2208.062500,1705.059674,10894.5,22.0,3377.260870,2819.217391,3543.118421,26.667620,86.250000,7.760392,26.135618,88.801075,7.522984,27.325972,87.202778,6.930694,30.036828,72.215054,8.187769,38.0,44.0,68.0,53.0,1,2273.291450,218.075214,11.2,47.0,24.2,1.055721,0.866461,1.018397,1.398285,1.398285,0.25
252,2024-10-01,COK,3087.5,22.7,33.0,27.075538,56.0,100.0,84.256720,1.8,19.0,6.808199,33,1,2024,10,1,1,275,40,4,-8.660254e-01,5.000000e-01,0.781831,0.623490,-2.449294e-16,1.000000e+00,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,3087.5,1323.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,4024.500000,2386.038148,10894.5,2373.5,48294.0,2223.491228,1693.777523,10894.5,22.0,2796.326087,4429.753623,3893.842857,27.373112,83.048338,7.966767,26.667620,86.250000,7.760392,26.135618,88.801075,7.522984,30.990278,75.025000,7.883194,36.0,38.0,44.0,92.0,1,2281.296005,184.335646,10.3,44.0,17.2,1.054855,3.268091,0.985545,1.388582,1.388582,0.25
256,2024-11-01,COK,3087.5,23.0,34.0,27.243194,39.0,100.0,81.776389,2.0,20.0,6.193889,28,1,2024,11,1,4,306,44,4,-5.000000e-01,8.660254e-01,-0.433884,-0.900969,-2.449294e-16,1.000000e+00,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,3087.5,2373.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,4084.000000,2349.751312,10894.5,2478.5,49008.0,2238.387931,1682.682951,10894.5,22.0,2838.673913,4429.753623,6021.269231,27.075538,84.256720,6.808199,27.373112,83.048338,7.966767,26.667620,86.250000,7.760392,28.547177,82.731183,7.585081,33.0,36.0,38.0,100.0,1,2227.850063,168.741319,11.0,61.0,18.0,2.373075,0.265385,1.018397,1.379341,1.379341,0.25
260,2024-12-01,COK,3087.5,20.6,34.0,26.664809,39.0,100.0,80.067449,1.4,20.0,6.526872,26,3,2024,12,1,6,336,48,4,-2.449294e-16,1.000000e+00,-0.781831,0.623490,-2.449294e-16,1.000000e+00,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,3087.5,5437.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3888.208333,2324.514304,10894.5,2478.5,46658.5,2252.779661,1671.772857,10894.5,22.0,7654.260870,4429.753623,3543.118421,27.243194,81.776389,6.193889,27.075538,84.256720,6.808199,27.373112,83.048338,7.966767,27.325972,87.202778,6.930694,28.0,33.0,36.0,68.0,1,2134.983257,174.037804,13.4,61.0,18.6,2.656090,1.162700,0.985545,1.370529,1.370529,0.25
264,2025-01-01,COK,3087.5,20.0,35.2,27.200672,25.0,100.0,68.475806,1.8,20.0,6.800134,30,2,2025,1,1,2,1,1,1,5.000000e-01,8.660254e-01,0.974928,-0.222521,1.000000e+00,6.123234e-17,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,3087.5,2478.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3938.958333,2297.429072,10894.5,3087.5,47267.5,2266.691667,1661.044013,10894.5,22.0,3915.062500,5797.812500,4773.453488,26.664809,80.067449,6.526872,27.243194,81.776389,6.193889,27.075538,84.256720,6.808199,26.135618,88.801075,7.522984,26.0,28.0,33.0,44.0,1,1862.587954,184.968226,15.2,75.0,18.2,2.894473,-4.137508,1.018397,1.362117,1.362117,0.25
268,2025-02-01,COK,3087.5,20.0,37.0,27.954613,23.0,100.0,70.589286,1.4,22.0,7.007738,40,3,2025,2,1,5,32,5,1,8.660254e-01,5.000000e-01,-0.974928,-0.222521,1.000000e+00,6.123234e-17,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,3087.5,5498.0,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3738.083333,2253.686776,10894.5,3087.5,44857.0,2280.147541,1650.493094,10894.5,22.0,6437.520833,5797.812500,3595.895349,27.200672,68.475806,6.800134,26.664809,80.067449,6.526872,27.243194,81.776389,6.193889,26.667620,86.250000,7.760392,30.0,26.0,28.0,38.0,1,1973.296171,195.898607,17.0,77.0,20.6,2.369877,6.483781,1.018397,1.354079,1.354079,0.25
272,2025-03-01,COK,3087.5,23.0,37.0,28.886557,27.0,100.0,76.334426,0.7,22.0,7.503115,65,3,2025,3,1,5,60,9,1,1.000000e+00,6.123234e-17,-0.974928,-0.222521,1.000000e+00,6.123234e-17,3087.5,3087.5,3087.5,3087.50,3087.5,3087.500000,3087.5,10894.5,3087.50,0.000000,3087.5,3087.5,6175.0,3087.500000,0.000000,3087.5,3087.5,9262.5,3087.500000,0.000000,3087.5,3087.5,18525.0,3087.500000,0.000000,3087.5,3087.5,37050.0,2293.169355,1640.116709,10894.5,22.0,7040.854167,5797.812500,3595.895349,27.954613,70.589286,7.007738,27.200672,68.475806,6.800134,26.664809,80.067449,6.526872,27.373112,83.048338,7.966767,40.0,30.0,26.0,36.0,1,2205.038783,216.739155,14.0,73.0,21.3,1.052263,14.487194,0.919842,1.346390,1.346390,0.25
229,2024-04-01,MAA,3087.5,26.6,39.0,31.515278,31.0,92.0,72.612500,0.0,27.7,11.727083,92,3,2024,4,1,0,92,14,2,8.660254e-01,-5.000000e-01,0.000000,1.000000,1.224647e-16,-1.000000e+00,21649.0,21649.0,13451.0,11582.75,9714.5,11427.166667,5695.0,19518.5,12368.25,13124.962519,21649.0,3087.5,24736.5,12729.166667,9301.779565,21649.0,3087.5,38187.5,12078.166667,7186.639031,21649.0,3087.5,72469.0,9794.333333,5788.739804,21649.0,3087.5,117532.0,7987.691667,5073.079199,22719.0,1130.0,7434.368421,4631.123077,4106.321429,29.282661,72.563172,10.352957,27.790661,74.606322,9.481034,26.239785,77.649194,7.772581,29.112500,80.241935,8.637634,53.0,34.0,28.0,30.0,2,2288.403108,369.582289,12.4,61.0,27.7,2.006007,10.185148,1.018397,1.593598,1.512097,0.25

In [254]:
fs_df = pd.read_csv('../data/Final Sales.csv')

In [262]:
fs_df['Date'] = pd.to_datetime(fs_df['Date'])

In [267]:
grouped_data = (
    fs_df.groupby([fs_df['Date'].dt.to_period('M').dt.to_timestamp().rename('MonthStart'), 'Branch'])
    .agg({'Sales Qty.': 'sum'})
    .reset_index()
)
grouped_data.columns = ['Date', 'Branch', 'Qty']

In [270]:
grouped_data[(grouped_data['Date'] >= '2024-04-01') & (grouped_data['Date'] <= '2025-03-01') & (grouped_data['Branch'] != 'VIJAYAWADA')]

          Date     Branch      Qty
138 2024-04-01  BANGALORE   6232.0
139 2024-04-01    CHENNAI  37511.0
140 2024-04-01     COCHIN  13241.0
141 2024-04-01  HYDERABAD  23754.0
143 2024-05-01  BANGALORE   4523.0
144 2024-05-01    CHENNAI  20702.0
145 2024-05-01     COCHIN   6120.0
146 2024-05-01  HYDERABAD  11406.0
148 2024-06-01  BANGALORE   2515.0
149 2024-06-01    CHENNAI   6720.0
150 2024-06-01     COCHIN   1594.0
151 2024-06-01  HYDERABAD   4796.0
153 2024-07-01  BANGALORE   2003.0
154 2024-07-01    CHENNAI   5597.0
155 2024-07-01     COCHIN   2680.0
156 2024-07-01  HYDERABAD   2000.0
158 2024-08-01  BANGALORE   2415.0
159 2024-08-01    CHENNAI   7844.0
160 2024-08-01     COCHIN   4886.0
161 2024-08-01  HYDERABAD   4774.0
163 2024-09-01  BANGALORE   3681.0
164 2024-09-01    CHENNAI  10063.0
165 2024-09-01     COCHIN   4885.0
166 2024-09-01  HYDERABAD   6800.0
168 2024-10-01  BANGALORE   2399.0
169 2024-10-01    CHENNAI   7804.0
170 2024-10-01     COCHIN   2124.0
171 2024-10-01  HYDERABAD   5801.0
173 2024-11-01  BANGALORE   2368.0
174 2024-11-01    CHENNAI   5992.0
175 2024-11-01     COCHIN   2991.0
176 2024-11-01  HYDERABAD   3893.0
178 2024-12-01  BANGALORE   5283.0
179 2024-12-01    CHENNAI  26889.0
180 2024-12-01     COCHIN   6536.0
181 2024-12-01  HYDERABAD  18118.0
183 2025-01-01  BANGALORE   4622.0
184 2025-01-01    CHENNAI  12963.0
185 2025-01-01     COCHIN   3617.0
186 2025-01-01  HYDERABAD  10901.0
188 2025-02-01  BANGALORE   5220.0
189 2025-02-01    CHENNAI  14232.0
190 2025-02-01     COCHIN   7575.0
191 2025-02-01  HYDERABAD  13269.0
193 2025-03-01  BANGALORE   8757.0
194 2025-03-01    CHENNAI  20042.0
195 2025-03-01     COCHIN  11052.0
196 2025-03-01  HYDERABAD  29239.0